In [20]:
import pandas as pd

df_train = pd.read_csv("./metadata_split/train_metaData.csv")
df_val = pd.read_csv("./metadata_split/val_metaData.csv")
df_test = pd.read_csv("./metadata_split/test_metaData.csv")

drop_cols = ["image", "filename", "stem", "Date", "donor_id", "unique_donor_id", "year.1"]

drop_cols_all = drop_cols

df_reduced_train = df_train.drop(columns=drop_cols_all, errors="ignore")
df_reduced_val = df_val.drop(columns=drop_cols_all, errors="ignore")
df_reduced_test = df_test.drop(columns=drop_cols_all, errors="ignore")

print("Remaining columns:", df_reduced_train.columns.tolist())
print("Num remaining:", len(df_reduced_train.columns))

Remaining columns: ['class_label', 'year', 'wind_dir', 'season', 'img_f397', 'img_f492', 'img_f339', 'img_f392', 'img_f142', 'img_f311', 'img_f743', 'img_f888', 'img_f1947', 'img_f1763', 'img_f1123', 'img_f1806', 'img_f1713', 'img_f1549', 'img_f1260', 'img_f1105', 'img_f1018', 'img_f27', 'img_f38', 'img_f840', 'img_f1639', 'img_f92', 'img_f764', 'img_f14', 'img_f1170', 'img_f496', 'img_f717', 'img_f879', 'img_f558', 'img_f1871', 'img_f1133', 'img_f994', 'img_f335', 'img_f1309', 'img_f1271', 'img_f809', 'img_f2047', 'img_f987', 'img_f30', 'img_f1373', 'img_f1458', 'img_f58', 'img_f1295', 'img_f1625', 'img_f1243', 'img_f674', 'img_f246', 'img_f1998', 'img_f744', 'img_f1501', 'img_f657', 'img_f898', 'img_f974', 'img_f1924', 'img_f1881', 'img_f211', 'img_f931', 'img_f1411', 'img_f1204', 'img_f93', 'img_f2042', 'img_f410', 'img_f1985', 'img_f1572', 'img_f379', 'img_f21', 'img_f459', 'img_f798', 'img_f1635', 'img_f1391', 'img_f1199', 'img_f248', 'img_f1016', 'img_f1423', 'img_f1000', 'img_f1457', 'img_f88', 'img_f175', 'img_f926', 'img_f753', 'img_f250', 'img_f1388', 'img_f370', 'img_f357', 'img_f1844', 'img_f446', 'img_f1805', 'img_f1327', 'img_f324', 'img_f1696', 'img_f1014', 'img_f1281', 'img_f1611', 'img_f104', 'img_f667', 'img_f531', 'img_f683', 'img_f1542', 'img_f886', 'img_f826', 'img_f1975', 'img_f1721', 'img_f1350', 'img_f903', 'img_f1648', 'img_f1320', 'img_f1555', 'img_f1599', 'img_f1995', 'img_f279', 'img_f1408', 'img_f746', 'img_f1477', 'img_f1800', 'img_f1808', 'img_f513', 'img_f1944', 'img_f1394', 'img_f833', 'img_f541', 'img_f1732', 'img_f1854', 'img_f600', 'img_f1030', 'img_f1058', 'img_f2017', 'img_f381', 'img_f922', 'img_f1368', 'img_f1502', 'img_f851', 'img_f1113', 'img_f1041', 'img_f942', 'img_f215', 'img_f234', 'img_f1444', 'img_f647', 'img_f1426', 'img_f990', 'img_f693', 'img_f15', 'img_f935', 'img_f1168', 'img_f1242', 'img_f1167', 'img_f984', 'img_f26', 'img_f756', 'img_f179', 'img_f741', 'img_f1865', 'img_f1943', 'img_f1942', 'img_f1342', 'img_f151', 'img_f29', 'img_f1567', 'img_f507', 'img_f241', 'img_f1910', 'img_f60', 'img_f2031', 'img_f817', 'img_f1049', 'img_f1968', 'img_f981', 'img_f1546', 'img_f91', 'img_f323', 'img_f701', 'img_f1205', 'img_f1716', 'img_f1843', 'img_f1071', 'img_f1107', 'img_f1463', 'img_f1752', 'img_f1946', 'img_f1864', 'img_f1631', 'img_f1165', 'img_f788', 'img_f1901', 'img_f1905', 'img_f745', 'img_f1667', 'img_f469', 'img_f36', 'img_f2002', 'img_f999', 'img_f1331', 'img_f1238', 'img_f1307', 'img_f580', 'img_f1355', 'img_f1068', 'img_f1382', 'img_f1972', 'img_f1509', 'img_f398', 'img_f134', 'img_f1337', 'img_f528', 'img_f697', 'img_f1379', 'img_f1691', 'img_f839', 'img_f847', 'img_f723', 'img_f725', 'img_f1479', 'img_f1442', 'img_f282', 'img_f445', 'img_f438', 'img_f1566', 'img_f1613', 'img_f1994', 'img_f966', 'img_f1403', 'img_f125', 'img_f116', 'img_f114', 'img_f1616', 'img_f238', 'img_f1700', 'img_f97', 'img_f1178', 'img_f526', 'img_f42', 'img_f1038', 'img_f1034', 'img_f1027', 'img_f1819', 'img_f1480', 'img_f767', 'img_f636', 'img_f1971', 'img_f52', 'img_f1347', 'img_f1142', 'img_f1967', 'img_f1916', 'img_f1893', 'img_f1877', 'img_f304', 'img_f1356', 'img_f593', 'img_f1308', 'img_f236', 'img_f242', 'img_f220', 'img_f183', 'img_f1641', 'img_f810', 'img_f1078', 'img_f1301', 'img_f5', 'img_f18', 'Wind_Run', 'img_f911', 'img_f890', 'img_f1551', 'img_f1534', 'img_f1545', 'img_f368', 'img_f364', 'img_f1973', 'img_f1535', 'img_f1001', 'img_f721', 'img_f353', 'img_f1588', 'img_f1558', 'img_f2023', 'img_f1596', 'img_f385', 'img_f396', 'img_f1478', 'img_f422', 'img_f1640', 'img_f835', 'img_f1076', 'img_f1315', 'img_f1303', 'img_f581', 'img_f219', 'img_f224', 'img_f1719', 'img_f1729', 'img_f1727', 'img_f557', 'img_f564', 'img_f49', 'img_f1248', 'img_f1244', 'img_f616', 'img_f1270', 'img_f1291', 'img_f300', 'img_f1139', 'img_f759', 'img_f1785', 'img_f630', 'img_f650', 'img_f1267', 'img_f1949', 'img_f758', 'img_f1120', 'img_f1821', 'img_f144', 'img_f698', 'img_f1214', 'img_f659', 'img_f1799', 'img_f988', 'img_f781', 'img_f94', 'img_f1192', 'img_f1201', 'img_f532', 'img_f515', 'img_f245', 'img_f262', 'img_f269', 'img_f1158', 'img_f1415', 'img_f494', 'img_f1404', 'img_f132', 'img_f390', 'img_f28', 'img_f7', 'img_f358', 'img_f747', 'img_f1164', 'img_f1064', 'img_f818', 'img_f789', 'img_f1751', 'img_f1330', 'img_f405', 'img_f1525', 'img_f2001', 'img_f1980', 'img_f1789', 'img_f1595', 'img_f320', 'img_f317', 'img_f394', 'img_f342', 'img_f354', 'img_f933', 'img_f752', 'img_f129', 'img_f126', 'img_f140', 'img_f1400', 'img_f499', 'img_f497', 'img_f281', 'img_f272', 'img_f1439', 'img_f1460', 'img_f452', 'img_f449', 'img_f512', 'img_f254', 'img_f251', 'img_f1699', 'img_f1702', 'img_f1173', 'img_f518', 'img_f1100', 'img_f1081', 'img_f89', 'img_f1834', 'img_f1817', 'img_f1814', 'img_f705', 'img_f1896', 'img_f78', 'img_f1883', 'img_f1127', 'img_f1121', 'img_f53', 'img_f1909', 'img_f1965', 'img_f1361', 'img_f1338', 'img_f1147', 'img_f150', 'img_f149', 'img_f1822', 'img_f1726', 'img_f556', 'img_f585', 'img_f218', 'img_f1765', 'img_f1047', 'img_f1492', 'img_f444', 'img_f1473', 'img_f413', 'img_f194', 'img_f189', 'img_f209', 'img_f1774', 'img_f186', 'img_f1772', 'img_f1769', 'img_f303', 'img_f418', 'img_f415', 'img_f1512', 'img_f1506', 'img_f633', 'img_f612', 'img_f1284', 'img_f1505', 'img_f983', 'img_f1959', 'img_f1948', 'img_f1792', 'img_f652', 'img_f651', 'img_f846', 'img_f1500', 'img_f1608', 'img_f2011', 'img_f1219', 'img_f1226', 'img_f658', 'img_f2014', 'img_f856', 'img_f854', 'img_f1003', 'img_f352', 'img_f345', 'img_f1528', 'img_f862', 'img_f1536', 'img_f13', 'img_f9', 'img_f1868', 'img_f107', 'img_f105', 'img_f733', 'img_f505', 'img_f2027', 'img_f2028', 'img_f939', 'img_f928', 'img_f917', 'img_f1802', 'img_f1811', 'img_f170', 'img_f162', 'img_f166', 'img_f174', 'img_f1788', 'img_f632', 'img_f1804', 'img_f1268', 'img_f1180', 'img_f583', 'img_f675', 'img_f671', 'img_f1176', 'img_f1187', 'img_f1181', 'img_f822', 'img_f45', 'img_f1941', 'img_f31', 'img_f827', 'img_f40', 'img_f51', 'img_f47', 'img_f1036', 'img_f1954', 'img_f1614', 'img_f403', 'img_f1011', 'img_f591', 'img_f1299', 'img_f610', 'img_f595', 'img_f1236', 'img_f1809', 'img_f1755', 'img_f614', 'img_f1285', 'img_f1813', 'img_f1498', 'img_f1503', 'img_f465', 'img_f409', 'img_f463', 'img_f1481', 'img_f299', 'img_f1544', 'img_f373', 'img_f330', 'img_f329', 'img_f325', 'img_f295', 'img_f1510', 'img_f1521', 'img_f1630', 'img_f548', 'img_f550', 'img_f561', 'img_f1766', 'img_f1775', 'img_f1758', 'img_f1757', 'img_f188', 'img_f185', 'img_f1753', 'img_f700', 'img_f1845', 'img_f1859', 'img_f736', 'img_f1657', 'img_f1446', 'img_f1662', 'img_f273', 'img_f1092', 'img_f1106', 'img_f1103', 'img_f804', 'img_f79', 'img_f400', 'img_f54', 'img_f67', 'img_f64', 'img_f510', 'img_f530', 'img_f1701', 'img_f111', 'img_f229', 'img_f737', 'img_f1743', 'img_f567', 'img_f1118', 'img_f1906', 'img_f1903', 'img_f772', 'img_f1152', 'img_f500', 'img_f495', 'img_f277', 'img_f501', 'img_f516', 'img_f1349', 'img_f288', 'img_f286', 'img_f1392', 'img_f1432', 'img_f1376', 'img_f1387', 'img_f1383', 'img_f1381', 'img_f1429', 'img_f1440', 'img_f473', 'img_f472', 'img_f471', 'img_f127', 'img_f138', 'img_f508', 'img_f1698', 'img_f1116', 'img_f813', 'img_f1056', 'img_f807', 'img_f820', 'img_f1088', 'img_f1067', 'img_f1065', 'img_f797', 'img_f423', 'img_f1465', 'img_f1471', 'img_f1999', 'img_f1007', 'img_f2003', 'img_f34', 'img_f343', 'img_f356', 'img_f363', 'img_f959', 'img_f957', 'img_f972', 'img_f1577', 'img_f1793', 'img_f1297', 'img_f210', 'img_f1617', 'img_f971', 'img_f970', 'img_f841', 'img_f877', 'img_f964', 'img_f16', 'img_f918', 'img_f8', 'img_f1782', 'img_f1801', 'img_f160', 'img_f171', 'img_f1279', 'img_f1796', 'img_f948', 'img_f946', 'img_f3', 'img_f4', 'img_f936', 'img_f968', 'img_f1024', 'img_f1033', 'img_f1029', 'img_f843', 'img_f842', 'img_f1590', 'img_f1600', 'img_f386', 'img_f382', 'img_f318', 'img_f1618', 'img_f1791', 'img_f1298', 'img_f1296', 'img_f603', 'img_f1586', 'img_f348', 'img_f346', 'temp_high', 'img_f361', 'img_f366', 'img_f1526', 'img_f23', 'img_f2000', 'img_f1997', 'img_f884', 'img_f2029', 'img_f860', 'img_f873', 'img_f314', 'img_f1663', 'img_f1462', 'img_f1482', 'img_f1650', 'img_f1649', 'img_f1090', 'img_f812', 'img_f751', 'img_f750', 'img_f1114', 'img_f819', 'img_f1138', 'img_f761', 'img_f1422', 'img_f484', 'img_f1708', 'img_f1438', 'img_f470', 'img_f263', 'img_f1431', 'img_f1386', 'img_f1348', 'img_f1343', 'img_f1334', 'img_f498', 'img_f1683', 'img_f1680', 'img_f1886', 'img_f1900', 'img_f1895', 'img_f1908', 'img_f726', 'img_f738', 'img_f214', 'img_f213', 'img_f560', 'img_f231', 'img_f588', 'img_f1737', 'img_f1744', 'img_f260', 'img_f256', 'img_f268', 'img_f514', 'img_f522', 'img_f1705', 'img_f1709', 'img_f419', 'img_f1499', 'img_f62', 'img_f831', 'img_f82', 'img_f81', 'img_f1929', 'img_f1936', 'img_f784', 'img_f783', 'img_f1083', 'img_f1077', 'img_f75', 'img_f1095', 'img_f85', 'img_f778', 'img_f1455', 'img_f1675', 'img_f271', 'img_f109', 'img_f731', 'img_f122', 'img_f131', 'img_f130', 'img_f102', 'img_f1200', 'img_f707', 'img_f709', 'img_f724', 'img_f136', 'img_f135', 'img_f1189', 'img_f1316', 'img_f1749', 'img_f1776', 'img_f1740', 'img_f1357', 'img_f1621', 'img_f1629', 'img_f1643', 'img_f416', 'img_f1550', 'img_f1633', 'img_f1548', 'img_f442', 'img_f450', 'img_f454', 'img_f436', 'img_f1435', 'img_f1494', 'img_f466', 'img_f464', 'img_f1519', 'img_f538', 'img_f1818', 'img_f1825', 'img_f714', 'img_f1841', 'img_f1839', 'img_f133', 'img_f1235', 'img_f609', 'img_f607', 'img_f621', 'img_f1239', 'img_f1247', 'img_f597', 'img_f611', 'img_f594', 'img_f1306', 'img_f1302', 'img_f626', 'img_f623', 'img_f1311', 'img_f1317', 'img_f1012', 'img_f1609', 'img_f864', 'img_f1957', 'img_f992', 'img_f989', 'img_f37', 'img_f48', 'img_f1952', 'img_f1963', 'img_f1037', 'img_f44', 'img_f828', 'img_f824', 'img_f1912', 'img_f1919', 'img_f1917', 'img_f1931', 'img_f1074', 'img_f582', 'img_f1196', 'img_f665', 'img_f663', 'img_f1254', 'img_f691', 'img_f689', 'img_f638', 'img_f161', 'img_f927', 'img_f1', 'img_f1974', 'img_f2019', 'img_f945', 'img_f943', 'img_f2034', 'img_f1579', 'img_f1565', 'img_f2012', 'img_f2009', 'img_f2008', 'img_f1569', 'img_f2006', 'img_f889', 'img_f885', 'img_f2038', 'img_f2026', 'img_f2021', 'img_f919', 'img_f930', 'img_f1988', 'img_f1987', 'img_f1984', 'img_f1996', 'img_f1991', 'img_f1989', 'img_f861', 'img_f1002', 'img_f1009', 'img_f1610', 'img_f1605', 'img_f404', 'img_f333', 'img_f1592', 'img_f1591', 'img_f1958', 'img_f1021', 'img_f1035', 'img_f858', 'img_f853', 'img_f866', 'img_f865', 'img_f1004', 'img_f1624', 'img_f1523', 'img_f1969', 'img_f1075', 'img_f1073', 'img_f836', 'img_f1945', 'img_f1956', 'img_f1553', 'img_f1636', 'img_f1632', 'img_f1644', 'img_f1638', 'img_f298', 'img_f297', 'img_f1628', 'img_f1221', 'img_f1810', 'img_f1754', 'img_f645', 'img_f654', 'img_f1210', 'img_f1208', 'img_f1835', 'img_f628', 'img_f1251', 'img_f1250', 'img_f606', 'img_f620', 'img_f1300', 'img_f1216', 'img_f1224', 'img_f682', 'img_f1207', 'img_f1206', 'img_f1217', 'img_f1321', 'img_f1325', 'img_f1274', 'img_f596', 'img_f1257', 'img_f1255', 'img_f1261', 'img_f635', 'img_f1182', 'img_f662', 'img_f676', 'img_f672', 'img_f1768', 'img_f1313', 'img_f1312', 'img_f710', 'img_f1194', 'img_f1193', 'img_f1197', 'img_f695', 'img_f549', 'img_f562', 'img_f1773', 'img_f184', 'img_f195', 'img_f1273', 'img_f1761', 'img_f1771', 'img_f1827', 'img_f716', 'img_f711', 'img_f574', 'img_f1720', 'img_f1728', 'img_f1725', 'img_f1360', 'img_f1833', 'img_f1831', 'img_f152', 'img_f164', 'img_f163', 'img_f147', 'img_f146', 'img_f1815', 'img_f720', 'img_f1143', 'img_f1150', 'img_f1162', 'img_f1157', 'img_f1172', 'img_f1898', 'img_f90', 'img_f584', 'img_f1735', 'img_f1742', 'img_f1741', 'img_f570', 'img_f728', 'img_f739', 'img_f722', 'img_f730', 'img_f527', 'img_f253', 'img_f267', 'img_f228', 'img_f223', 'img_f222', 'img_f244', 'img_f1857', 'img_f1875', 'img_f1873', 'img_f123', 'img_f120', 'img_f748', 'img_f110', 'img_f732', 'img_f240', 'img_f1690', 'img_f1689', 'img_f1686', 'img_f1695', 'img_f1707', 'img_f493', 'img_f1406', 'img_f1341', 'img_f1370', 'img_f1369', 'img_f1377', 'img_f265', 'img_f1434', 'img_f1441', 'img_f1452', 'img_f1125', 'img_f490', 'img_f489', 'img_f292', 'img_f291', 'img_f290', 'img_f1389', 'img_f1345', 'img_f87', 'img_f86', 'img_f1878', 'img_f1889', 'img_f1888', 'img_f1885', 'img_f1899', 'img_f1129', 'img_f1653', 'img_f1668', 'img_f1661', 'img_f1674', 'img_f1670', 'img_f270', 'img_f1660', 'img_f1659', 'img_f806', 'img_f805', 'img_f1091', 'img_f1474', 'img_f1647', 'img_f316', 'img_f426', 'img_f421', 'img_f763', 'img_f128', 'img_f1109', 'img_f1055', 'img_f1066', 'img_f1061', 'img_f801', 'img_f811', 'img_f1413', 'img_f1427', 'img_f1424', 'img_f1421', 'img_f479', 'img_f491', 'img_f1137', 'img_f1135', 'img_f447', 'img_f431', 'img_f1467', 'img_f340', 'img_f337', 'img_f1537', 'img_f1533', 'img_f1541', 'img_f1496', 'img_f1515', 'img_f462', 'img_f461', 'img_f1436', 'img_f1489', 'img_f443', 'img_f439', 'img_f83', 'img_f1926', 'img_f56', 'img_f832', 'img_f1970', 'img_f1517', 'img_f407', 'img_f402', 'img_f1656', 'img_f1655', 'img_f476', 'img_f1097', 'img_f108', 'img_f61', 'img_f76', 'img_f73', 'img_f6', 'img_f11', 'img_f0', 'img_f2', 'img_f2039', 'img_f870', 'img_f973', 'img_f892', 'img_f955', 'img_f1564', 'img_f1557', 'img_f2020', 'img_f2007', 'img_f17', 'img_f1025', 'img_f1023', 'img_f895', 'img_f906', 'img_f904', 'img_f914', 'img_f920', 'img_f980', 'img_f1603', 'img_f1597', 'img_f1612', 'img_f1031', 'img_f1043', 'img_f1040', 'img_f844', 'img_f1017', 'img_f1790', 'img_f1783', 'img_f634', 'img_f631', 'img_f641', 'img_f639', 'img_f1245', 'img_f1258', 'wind_speed', 'img_f1293', 'img_f191', 'img_f190', 'img_f207', 'img_f1278', 'img_f1292', 'img_f1290', 'img_f880', 'img_f359', 'img_f1539', 'img_f1573', 'img_f1587', 'img_f1585', 'img_f344', 'img_f2037', 'img_f869', 'img_f1979', 'img_f1977', 'img_f1008', 'img_f963', 'img_f960', 'img_f35', 'img_f32', 'img_f2024', 'img_f2022', 'img_f20', 'img_f63', 'img_f941', 'img_f921', 'img_f947', 'img_f908', 'img_f907', 'img_f929', 'img_f925', 'img_f1953', 'img_f1951', 'img_f1950', 'img_f910', 'img_f1935', 'img_f71', 'img_f1923', 'img_f55', 'img_f1911', 'img_f1966', 'img_f1928', 'img_f112', 'img_f1920', 'img_f1915', 'img_f1907', 'img_f1904', 'img_f1848', 'img_f1847', 'img_f1890', 'img_f100', 'img_f99', 'img_f1892', 'img_f139', 'img_f1880', 'img_f1879', 'img_f84', 'img_f976', 'img_f905', 'img_f902', 'img_f900', 'img_f958', 'img_f891', 'img_f887', 'img_f969', 'img_f962', 'img_f953', 'img_f951', 'img_f949', 'img_f1876', 'img_f1872', 'img_f145', 'img_f1861', 'img_f1860', 'img_f1851', 'img_f1850', 'img_f1870', 'img_f1866', 'img_f173', 'img_f1853', 'img_f158', 'img_f157', 'img_f1784', 'img_f1840', 'img_f172', 'img_f169', 'img_f1824', 'img_f1823', 'img_f155', 'img_f153', 'img_f196', 'img_f193', 'img_f1832', 'img_f1829', 'img_f1828', 'img_f1006', 'img_f1005', 'img_f876', 'img_f875', 'img_f872', 'img_f986', 'img_f982', 'img_f857', 'img_f855', 'img_f1026', 'img_f1022', 'img_f997', 'img_f993', 'img_f991', 'img_f1042', 'img_f1032', 'img_f1779', 'img_f1778', 'img_f1777', 'img_f202', 'img_f201', 'img_f1759', 'img_f1750', 'img_f192', 'img_f1794', 'img_f1770', 'img_f1764', 'img_f1812', 'img_f1803', 'img_f823', 'img_f1015', 'img_f1013', 'img_f852', 'img_f1060', 'img_f1059', 'img_f834', 'img_f830', 'img_f1048', 'img_f1046', 'img_f1072', 'img_f1063', 'img_f1062', 'img_f871', 'img_f867', 'img_f1053', 'img_f1052', 'img_f1051', 'img_f1723', 'img_f205', 'img_f203', 'img_f1736', 'img_f1734', 'img_f1733', 'img_f264', 'img_f261', 'img_f259', 'img_f1718', 'img_f212', 'img_f208', 'img_f206', 'img_f1108', 'img_f816', 'img_f814', 'img_f808', 'img_f1093', 'img_f794', 'img_f1082', 'img_f1079', 'img_f1102', 'img_f849', 'img_f845', 'img_f1085', 'img_f247', 'img_f1715', 'img_f276', 'img_f266', 'img_f1694', 'img_f252', 'img_f249', 'img_f239', 'img_f1712', 'img_f1706', 'img_f1704', 'img_f301', 'img_f296', 'img_f1688', 'img_f1687', 'img_f769', 'img_f766', 'img_f1136', 'img_f1134', 'img_f775', 'img_f774', 'img_f770', 'img_f1122', 'img_f1117', 'img_f760', 'img_f757', 'img_f799', 'img_f1131', 'img_f1130', 'img_f1128', 'img_f1126', 'img_f280', 'img_f308', 'img_f307', 'img_f305', 'img_f1678', 'img_f1677', 'img_f293', 'img_f289', 'img_f1658', 'img_f1679', 'img_f1671', 'img_f1171', 'img_f1111', 'img_f735', 'img_f729', 'img_f727', 'img_f1141', 'img_f1161', 'img_f1156', 'img_f779', 'img_f776', 'img_f1151', 'img_f1149', 'img_f1148', 'img_f322', 'img_f1601', 'img_f309', 'img_f334', 'img_f331', 'img_f328', 'img_f327', 'img_f1623', 'img_f315', 'img_f313', 'img_f310', 'img_f350', 'img_f1645', 'img_f1580', 'img_f355', 'img_f351', 'img_f1563', 'img_f1562', 'img_f1561', 'img_f341', 'img_f1584', 'img_f1581', 'img_f1607', 'img_f1606', 'img_f1575', 'img_f1574', 'img_f1571', 'img_f1570', 'img_f1560', 'img_f1615', 'img_f1202', 'img_f718', 'img_f715', 'img_f708', 'img_f1184', 'img_f1179', 'img_f696', 'img_f694', 'img_f1203', 'img_f687', 'img_f1191', 'img_f1188', 'img_f1186', 'img_f754', 'img_f1175', 'img_f692', 'img_f401', 'img_f399', 'img_f395', 'img_f1538', 'img_f384', 'img_f383', 'img_f380', 'img_f378', 'img_f377', 'img_f369', 'img_f367', 'img_f1554', 'img_f1552', 'img_f1543', 'img_f1530', 'img_f1529', 'img_f684', 'img_f1225', 'img_f670', 'img_f668', 'img_f664', 'img_f1212', 'img_f1211', 'img_f1209', 'img_f1230', 'img_f1228', 'img_f703', 'img_f1222', 'img_f1461', 'img_f435', 'img_f434', 'img_f433', 'img_f432', 'img_f1518', 'img_f1516', 'img_f1514', 'img_f424', 'img_f1497', 'img_f408', 'img_f1522', 'img_f457', 'img_f1511', 'img_f1508', 'img_f1504', 'img_f1265', 'img_f660', 'img_f649', 'img_f1249', 'img_f1246', 'img_f640', 'img_f629', 'img_f624', 'img_f1262', 'img_f1256', 'img_f1253', 'img_f677', 'img_f673', 'img_f1241', 'img_f441', 'img_f437', 'img_f1437', 'img_f1484', 'img_f456', 'img_f455', 'img_f1464', 'img_f1490', 'img_f1487', 'img_f1398', 'img_f1472', 'img_f1469', 'img_f1287', 'img_f617', 'img_f613', 'img_f608', 'img_f1275', 'img_f1272', 'img_f599', 'img_f1294', 'img_f1319', 'img_f1280', 'img_f648', 'img_f644', 'img_f1332', 'img_f1324', 'img_f482', 'img_f481', 'img_f1409', 'img_f1405', 'img_f1402', 'img_f1454', 'img_f1447', 'img_f1445', 'img_f478', 'img_f477', 'img_f475', 'img_f1367', 'img_f1453', 'img_f1449', 'img_f520', 'img_f519', 'img_f1375', 'img_f1374', 'img_f503', 'img_f502', 'img_f1428', 'img_f1414', 'img_f517', 'img_f536', 'img_f1425', 'img_f1420', 'img_f1418', 'img_f1417', 'img_f576', 'img_f573', 'img_f1318', 'img_f1304', 'img_f565', 'img_f559', 'img_f577', 'img_f545', 'img_f572', 'img_f568', 'img_f566', 'img_f604', 'img_f555', 'img_f1359', 'img_f1358', 'img_f539', 'img_f1363', 'img_f1390', 'img_f1384', 'img_f1353', 'img_f1346', 'img_f590', 'img_f589', 'img_f1333', 'img_f1395', 'img_f1393', 'temp_low', 'img_f2046', 'Heat_D-D', 'Temp_Out', 'img_f2044', 'img_f2013', 'img_f2010', 'img_f24', 'img_f1955', 'img_f1983', 'img_f1982', 'img_f50', 'img_f43', 'img_f41', 'img_f2033', 'img_f2032', 'img_f2030', 'img_f2004', 'img_f1993', 'img_f1992', 'img_f1990', 'img_f1981', 'img_f1978', 'img_f414', 'img_f1456', 'img_f1351', 'img_f554', 'img_f1894', 'img_f863', 'img_f1780', 'img_f243', 'img_f101', 'img_f1836', 'img_f1867', 'img_f59', 'img_f679', 'img_f1419']
Num remaining: 1542

In [22]:
import pandas as pd

df = df_reduced_train.copy()


label_map = {
    "FRESH": 0,
    "BLOAT": 1,
    "ACTIVE_DECAY": 2,
    "ADVANCED_DECAY": 3
}
df["class_label_encoded"] = df["class_label"].map(label_map)

# check mapping
print("Encoded target preview")
print(df[["class_label", "class_label_encoded"]].drop_duplicates())


numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
string_cols = df.select_dtypes(include=["object", "string"]).columns.tolist()


print("\nNumeric columns")
print(numeric_cols)

print("\nString columns")
print(string_cols)


print("\nString columns with unique counts")
for col in string_cols:
    print(f"{col}: unique={df[col].nunique(dropna=True)}, avg_len={df[col].astype(str).str.len().mean():.2f}")

target_col = "class_label_encoded"
raw_target_col = "class_label"


# input categorical columns only
categorical_cols = ["wind_dir", "season"]
categorical_cols = [c for c in categorical_cols if c in df.columns]

print("\nTarget column")
print(target_col)

print("\nInput categorical columns")
print(categorical_cols)


df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
df_encoded = df_encoded.drop(columns=[raw_target_col], errors="ignore")

print("\nFinal columns after one-hot encoding")
print(df_encoded.columns.tolist())

print("\nFinal shape")
print(df_encoded.shape)

df_encoded.to_csv("./metadata_split/train_processed_data.csv", index=False)
print("\nSaved to train processed_data.csv")

Encoded target preview
        class_label  class_label_encoded
0             FRESH                    0
47            BLOAT                    1
186    ACTIVE_DECAY                    2
290  ADVANCED_DECAY                    3

Numeric columns
['year', 'img_f397', 'img_f492', 'img_f339', 'img_f392', 'img_f142', 'img_f311', 'img_f743', 'img_f888', 'img_f1947', 'img_f1763', 'img_f1123', 'img_f1806', 'img_f1713', 'img_f1549', 'img_f1260', 'img_f1105', 'img_f1018', 'img_f27', 'img_f38', 'img_f840', 'img_f1639', 'img_f92', 'img_f764', 'img_f14', 'img_f1170', 'img_f496', 'img_f717', 'img_f879', 'img_f558', 'img_f1871', 'img_f1133', 'img_f994', 'img_f335', 'img_f1309', 'img_f1271', 'img_f809', 'img_f2047', 'img_f987', 'img_f30', 'img_f1373', 'img_f1458', 'img_f58', 'img_f1295', 'img_f1625', 'img_f1243', 'img_f674', 'img_f246', 'img_f1998', 'img_f744', 'img_f1501', 'img_f657', 'img_f898', 'img_f974', 'img_f1924', 'img_f1881', 'img_f211', 'img_f931', 'img_f1411', 'img_f1204', 'img_f93', 'img_f2042', 'img_f410', 'img_f1985', 'img_f1572', 'img_f379', 'img_f21', 'img_f459', 'img_f798', 'img_f1635', 'img_f1391', 'img_f1199', 'img_f248', 'img_f1016', 'img_f1423', 'img_f1000', 'img_f1457', 'img_f88', 'img_f175', 'img_f926', 'img_f753', 'img_f250', 'img_f1388', 'img_f370', 'img_f357', 'img_f1844', 'img_f446', 'img_f1805', 'img_f1327', 'img_f324', 'img_f1696', 'img_f1014', 'img_f1281', 'img_f1611', 'img_f104', 'img_f667', 'img_f531', 'img_f683', 'img_f1542', 'img_f886', 'img_f826', 'img_f1975', 'img_f1721', 'img_f1350', 'img_f903', 'img_f1648', 'img_f1320', 'img_f1555', 'img_f1599', 'img_f1995', 'img_f279', 'img_f1408', 'img_f746', 'img_f1477', 'img_f1800', 'img_f1808', 'img_f513', 'img_f1944', 'img_f1394', 'img_f833', 'img_f541', 'img_f1732', 'img_f1854', 'img_f600', 'img_f1030', 'img_f1058', 'img_f2017', 'img_f381', 'img_f922', 'img_f1368', 'img_f1502', 'img_f851', 'img_f1113', 'img_f1041', 'img_f942', 'img_f215', 'img_f234', 'img_f1444', 'img_f647', 'img_f1426', 'img_f990', 'img_f693', 'img_f15', 'img_f935', 'img_f1168', 'img_f1242', 'img_f1167', 'img_f984', 'img_f26', 'img_f756', 'img_f179', 'img_f741', 'img_f1865', 'img_f1943', 'img_f1942', 'img_f1342', 'img_f151', 'img_f29', 'img_f1567', 'img_f507', 'img_f241', 'img_f1910', 'img_f60', 'img_f2031', 'img_f817', 'img_f1049', 'img_f1968', 'img_f981', 'img_f1546', 'img_f91', 'img_f323', 'img_f701', 'img_f1205', 'img_f1716', 'img_f1843', 'img_f1071', 'img_f1107', 'img_f1463', 'img_f1752', 'img_f1946', 'img_f1864', 'img_f1631', 'img_f1165', 'img_f788', 'img_f1901', 'img_f1905', 'img_f745', 'img_f1667', 'img_f469', 'img_f36', 'img_f2002', 'img_f999', 'img_f1331', 'img_f1238', 'img_f1307', 'img_f580', 'img_f1355', 'img_f1068', 'img_f1382', 'img_f1972', 'img_f1509', 'img_f398', 'img_f134', 'img_f1337', 'img_f528', 'img_f697', 'img_f1379', 'img_f1691', 'img_f839', 'img_f847', 'img_f723', 'img_f725', 'img_f1479', 'img_f1442', 'img_f282', 'img_f445', 'img_f438', 'img_f1566', 'img_f1613', 'img_f1994', 'img_f966', 'img_f1403', 'img_f125', 'img_f116', 'img_f114', 'img_f1616', 'img_f238', 'img_f1700', 'img_f97', 'img_f1178', 'img_f526', 'img_f42', 'img_f1038', 'img_f1034', 'img_f1027', 'img_f1819', 'img_f1480', 'img_f767', 'img_f636', 'img_f1971', 'img_f52', 'img_f1347', 'img_f1142', 'img_f1967', 'img_f1916', 'img_f1893', 'img_f1877', 'img_f304', 'img_f1356', 'img_f593', 'img_f1308', 'img_f236', 'img_f242', 'img_f220', 'img_f183', 'img_f1641', 'img_f810', 'img_f1078', 'img_f1301', 'img_f5', 'img_f18', 'Wind_Run', 'img_f911', 'img_f890', 'img_f1551', 'img_f1534', 'img_f1545', 'img_f368', 'img_f364', 'img_f1973', 'img_f1535', 'img_f1001', 'img_f721', 'img_f353', 'img_f1588', 'img_f1558', 'img_f2023', 'img_f1596', 'img_f385', 'img_f396', 'img_f1478', 'img_f422', 'img_f1640', 'img_f835', 'img_f1076', 'img_f1315', 'img_f1303', 'img_f581', 'img_f219', 'img_f224', 'img_f1719', 'img_f1729', 'img_f1727', 'img_f557', 'img_f564', 'img_f49', 'img_f1248', 'img_f1244', 'img_f616', 'img_f1270', 'img_f1291', 'img_f300', 'img_f1139', 'img_f759', 'img_f1785', 'img_f630', 'img_f650', 'img_f1267', 'img_f1949', 'img_f758', 'img_f1120', 'img_f1821', 'img_f144', 'img_f698', 'img_f1214', 'img_f659', 'img_f1799', 'img_f988', 'img_f781', 'img_f94', 'img_f1192', 'img_f1201', 'img_f532', 'img_f515', 'img_f245', 'img_f262', 'img_f269', 'img_f1158', 'img_f1415', 'img_f494', 'img_f1404', 'img_f132', 'img_f390', 'img_f28', 'img_f7', 'img_f358', 'img_f747', 'img_f1164', 'img_f1064', 'img_f818', 'img_f789', 'img_f1751', 'img_f1330', 'img_f405', 'img_f1525', 'img_f2001', 'img_f1980', 'img_f1789', 'img_f1595', 'img_f320', 'img_f317', 'img_f394', 'img_f342', 'img_f354', 'img_f933', 'img_f752', 'img_f129', 'img_f126', 'img_f140', 'img_f1400', 'img_f499', 'img_f497', 'img_f281', 'img_f272', 'img_f1439', 'img_f1460', 'img_f452', 'img_f449', 'img_f512', 'img_f254', 'img_f251', 'img_f1699', 'img_f1702', 'img_f1173', 'img_f518', 'img_f1100', 'img_f1081', 'img_f89', 'img_f1834', 'img_f1817', 'img_f1814', 'img_f705', 'img_f1896', 'img_f78', 'img_f1883', 'img_f1127', 'img_f1121', 'img_f53', 'img_f1909', 'img_f1965', 'img_f1361', 'img_f1338', 'img_f1147', 'img_f150', 'img_f149', 'img_f1822', 'img_f1726', 'img_f556', 'img_f585', 'img_f218', 'img_f1765', 'img_f1047', 'img_f1492', 'img_f444', 'img_f1473', 'img_f413', 'img_f194', 'img_f189', 'img_f209', 'img_f1774', 'img_f186', 'img_f1772', 'img_f1769', 'img_f303', 'img_f418', 'img_f415', 'img_f1512', 'img_f1506', 'img_f633', 'img_f612', 'img_f1284', 'img_f1505', 'img_f983', 'img_f1959', 'img_f1948', 'img_f1792', 'img_f652', 'img_f651', 'img_f846', 'img_f1500', 'img_f1608', 'img_f2011', 'img_f1219', 'img_f1226', 'img_f658', 'img_f2014', 'img_f856', 'img_f854', 'img_f1003', 'img_f352', 'img_f345', 'img_f1528', 'img_f862', 'img_f1536', 'img_f13', 'img_f9', 'img_f1868', 'img_f107', 'img_f105', 'img_f733', 'img_f505', 'img_f2027', 'img_f2028', 'img_f939', 'img_f928', 'img_f917', 'img_f1802', 'img_f1811', 'img_f170', 'img_f162', 'img_f166', 'img_f174', 'img_f1788', 'img_f632', 'img_f1804', 'img_f1268', 'img_f1180', 'img_f583', 'img_f675', 'img_f671', 'img_f1176', 'img_f1187', 'img_f1181', 'img_f822', 'img_f45', 'img_f1941', 'img_f31', 'img_f827', 'img_f40', 'img_f51', 'img_f47', 'img_f1036', 'img_f1954', 'img_f1614', 'img_f403', 'img_f1011', 'img_f591', 'img_f1299', 'img_f610', 'img_f595', 'img_f1236', 'img_f1809', 'img_f1755', 'img_f614', 'img_f1285', 'img_f1813', 'img_f1498', 'img_f1503', 'img_f465', 'img_f409', 'img_f463', 'img_f1481', 'img_f299', 'img_f1544', 'img_f373', 'img_f330', 'img_f329', 'img_f325', 'img_f295', 'img_f1510', 'img_f1521', 'img_f1630', 'img_f548', 'img_f550', 'img_f561', 'img_f1766', 'img_f1775', 'img_f1758', 'img_f1757', 'img_f188', 'img_f185', 'img_f1753', 'img_f700', 'img_f1845', 'img_f1859', 'img_f736', 'img_f1657', 'img_f1446', 'img_f1662', 'img_f273', 'img_f1092', 'img_f1106', 'img_f1103', 'img_f804', 'img_f79', 'img_f400', 'img_f54', 'img_f67', 'img_f64', 'img_f510', 'img_f530', 'img_f1701', 'img_f111', 'img_f229', 'img_f737', 'img_f1743', 'img_f567', 'img_f1118', 'img_f1906', 'img_f1903', 'img_f772', 'img_f1152', 'img_f500', 'img_f495', 'img_f277', 'img_f501', 'img_f516', 'img_f1349', 'img_f288', 'img_f286', 'img_f1392', 'img_f1432', 'img_f1376', 'img_f1387', 'img_f1383', 'img_f1381', 'img_f1429', 'img_f1440', 'img_f473', 'img_f472', 'img_f471', 'img_f127', 'img_f138', 'img_f508', 'img_f1698', 'img_f1116', 'img_f813', 'img_f1056', 'img_f807', 'img_f820', 'img_f1088', 'img_f1067', 'img_f1065', 'img_f797', 'img_f423', 'img_f1465', 'img_f1471', 'img_f1999', 'img_f1007', 'img_f2003', 'img_f34', 'img_f343', 'img_f356', 'img_f363', 'img_f959', 'img_f957', 'img_f972', 'img_f1577', 'img_f1793', 'img_f1297', 'img_f210', 'img_f1617', 'img_f971', 'img_f970', 'img_f841', 'img_f877', 'img_f964', 'img_f16', 'img_f918', 'img_f8', 'img_f1782', 'img_f1801', 'img_f160', 'img_f171', 'img_f1279', 'img_f1796', 'img_f948', 'img_f946', 'img_f3', 'img_f4', 'img_f936', 'img_f968', 'img_f1024', 'img_f1033', 'img_f1029', 'img_f843', 'img_f842', 'img_f1590', 'img_f1600', 'img_f386', 'img_f382', 'img_f318', 'img_f1618', 'img_f1791', 'img_f1298', 'img_f1296', 'img_f603', 'img_f1586', 'img_f348', 'img_f346', 'temp_high', 'img_f361', 'img_f366', 'img_f1526', 'img_f23', 'img_f2000', 'img_f1997', 'img_f884', 'img_f2029', 'img_f860', 'img_f873', 'img_f314', 'img_f1663', 'img_f1462', 'img_f1482', 'img_f1650', 'img_f1649', 'img_f1090', 'img_f812', 'img_f751', 'img_f750', 'img_f1114', 'img_f819', 'img_f1138', 'img_f761', 'img_f1422', 'img_f484', 'img_f1708', 'img_f1438', 'img_f470', 'img_f263', 'img_f1431', 'img_f1386', 'img_f1348', 'img_f1343', 'img_f1334', 'img_f498', 'img_f1683', 'img_f1680', 'img_f1886', 'img_f1900', 'img_f1895', 'img_f1908', 'img_f726', 'img_f738', 'img_f214', 'img_f213', 'img_f560', 'img_f231', 'img_f588', 'img_f1737', 'img_f1744', 'img_f260', 'img_f256', 'img_f268', 'img_f514', 'img_f522', 'img_f1705', 'img_f1709', 'img_f419', 'img_f1499', 'img_f62', 'img_f831', 'img_f82', 'img_f81', 'img_f1929', 'img_f1936', 'img_f784', 'img_f783', 'img_f1083', 'img_f1077', 'img_f75', 'img_f1095', 'img_f85', 'img_f778', 'img_f1455', 'img_f1675', 'img_f271', 'img_f109', 'img_f731', 'img_f122', 'img_f131', 'img_f130', 'img_f102', 'img_f1200', 'img_f707', 'img_f709', 'img_f724', 'img_f136', 'img_f135', 'img_f1189', 'img_f1316', 'img_f1749', 'img_f1776', 'img_f1740', 'img_f1357', 'img_f1621', 'img_f1629', 'img_f1643', 'img_f416', 'img_f1550', 'img_f1633', 'img_f1548', 'img_f442', 'img_f450', 'img_f454', 'img_f436', 'img_f1435', 'img_f1494', 'img_f466', 'img_f464', 'img_f1519', 'img_f538', 'img_f1818', 'img_f1825', 'img_f714', 'img_f1841', 'img_f1839', 'img_f133', 'img_f1235', 'img_f609', 'img_f607', 'img_f621', 'img_f1239', 'img_f1247', 'img_f597', 'img_f611', 'img_f594', 'img_f1306', 'img_f1302', 'img_f626', 'img_f623', 'img_f1311', 'img_f1317', 'img_f1012', 'img_f1609', 'img_f864', 'img_f1957', 'img_f992', 'img_f989', 'img_f37', 'img_f48', 'img_f1952', 'img_f1963', 'img_f1037', 'img_f44', 'img_f828', 'img_f824', 'img_f1912', 'img_f1919', 'img_f1917', 'img_f1931', 'img_f1074', 'img_f582', 'img_f1196', 'img_f665', 'img_f663', 'img_f1254', 'img_f691', 'img_f689', 'img_f638', 'img_f161', 'img_f927', 'img_f1', 'img_f1974', 'img_f2019', 'img_f945', 'img_f943', 'img_f2034', 'img_f1579', 'img_f1565', 'img_f2012', 'img_f2009', 'img_f2008', 'img_f1569', 'img_f2006', 'img_f889', 'img_f885', 'img_f2038', 'img_f2026', 'img_f2021', 'img_f919', 'img_f930', 'img_f1988', 'img_f1987', 'img_f1984', 'img_f1996', 'img_f1991', 'img_f1989', 'img_f861', 'img_f1002', 'img_f1009', 'img_f1610', 'img_f1605', 'img_f404', 'img_f333', 'img_f1592', 'img_f1591', 'img_f1958', 'img_f1021', 'img_f1035', 'img_f858', 'img_f853', 'img_f866', 'img_f865', 'img_f1004', 'img_f1624', 'img_f1523', 'img_f1969', 'img_f1075', 'img_f1073', 'img_f836', 'img_f1945', 'img_f1956', 'img_f1553', 'img_f1636', 'img_f1632', 'img_f1644', 'img_f1638', 'img_f298', 'img_f297', 'img_f1628', 'img_f1221', 'img_f1810', 'img_f1754', 'img_f645', 'img_f654', 'img_f1210', 'img_f1208', 'img_f1835', 'img_f628', 'img_f1251', 'img_f1250', 'img_f606', 'img_f620', 'img_f1300', 'img_f1216', 'img_f1224', 'img_f682', 'img_f1207', 'img_f1206', 'img_f1217', 'img_f1321', 'img_f1325', 'img_f1274', 'img_f596', 'img_f1257', 'img_f1255', 'img_f1261', 'img_f635', 'img_f1182', 'img_f662', 'img_f676', 'img_f672', 'img_f1768', 'img_f1313', 'img_f1312', 'img_f710', 'img_f1194', 'img_f1193', 'img_f1197', 'img_f695', 'img_f549', 'img_f562', 'img_f1773', 'img_f184', 'img_f195', 'img_f1273', 'img_f1761', 'img_f1771', 'img_f1827', 'img_f716', 'img_f711', 'img_f574', 'img_f1720', 'img_f1728', 'img_f1725', 'img_f1360', 'img_f1833', 'img_f1831', 'img_f152', 'img_f164', 'img_f163', 'img_f147', 'img_f146', 'img_f1815', 'img_f720', 'img_f1143', 'img_f1150', 'img_f1162', 'img_f1157', 'img_f1172', 'img_f1898', 'img_f90', 'img_f584', 'img_f1735', 'img_f1742', 'img_f1741', 'img_f570', 'img_f728', 'img_f739', 'img_f722', 'img_f730', 'img_f527', 'img_f253', 'img_f267', 'img_f228', 'img_f223', 'img_f222', 'img_f244', 'img_f1857', 'img_f1875', 'img_f1873', 'img_f123', 'img_f120', 'img_f748', 'img_f110', 'img_f732', 'img_f240', 'img_f1690', 'img_f1689', 'img_f1686', 'img_f1695', 'img_f1707', 'img_f493', 'img_f1406', 'img_f1341', 'img_f1370', 'img_f1369', 'img_f1377', 'img_f265', 'img_f1434', 'img_f1441', 'img_f1452', 'img_f1125', 'img_f490', 'img_f489', 'img_f292', 'img_f291', 'img_f290', 'img_f1389', 'img_f1345', 'img_f87', 'img_f86', 'img_f1878', 'img_f1889', 'img_f1888', 'img_f1885', 'img_f1899', 'img_f1129', 'img_f1653', 'img_f1668', 'img_f1661', 'img_f1674', 'img_f1670', 'img_f270', 'img_f1660', 'img_f1659', 'img_f806', 'img_f805', 'img_f1091', 'img_f1474', 'img_f1647', 'img_f316', 'img_f426', 'img_f421', 'img_f763', 'img_f128', 'img_f1109', 'img_f1055', 'img_f1066', 'img_f1061', 'img_f801', 'img_f811', 'img_f1413', 'img_f1427', 'img_f1424', 'img_f1421', 'img_f479', 'img_f491', 'img_f1137', 'img_f1135', 'img_f447', 'img_f431', 'img_f1467', 'img_f340', 'img_f337', 'img_f1537', 'img_f1533', 'img_f1541', 'img_f1496', 'img_f1515', 'img_f462', 'img_f461', 'img_f1436', 'img_f1489', 'img_f443', 'img_f439', 'img_f83', 'img_f1926', 'img_f56', 'img_f832', 'img_f1970', 'img_f1517', 'img_f407', 'img_f402', 'img_f1656', 'img_f1655', 'img_f476', 'img_f1097', 'img_f108', 'img_f61', 'img_f76', 'img_f73', 'img_f6', 'img_f11', 'img_f0', 'img_f2', 'img_f2039', 'img_f870', 'img_f973', 'img_f892', 'img_f955', 'img_f1564', 'img_f1557', 'img_f2020', 'img_f2007', 'img_f17', 'img_f1025', 'img_f1023', 'img_f895', 'img_f906', 'img_f904', 'img_f914', 'img_f920', 'img_f980', 'img_f1603', 'img_f1597', 'img_f1612', 'img_f1031', 'img_f1043', 'img_f1040', 'img_f844', 'img_f1017', 'img_f1790', 'img_f1783', 'img_f634', 'img_f631', 'img_f641', 'img_f639', 'img_f1245', 'img_f1258', 'wind_speed', 'img_f1293', 'img_f191', 'img_f190', 'img_f207', 'img_f1278', 'img_f1292', 'img_f1290', 'img_f880', 'img_f359', 'img_f1539', 'img_f1573', 'img_f1587', 'img_f1585', 'img_f344', 'img_f2037', 'img_f869', 'img_f1979', 'img_f1977', 'img_f1008', 'img_f963', 'img_f960', 'img_f35', 'img_f32', 'img_f2024', 'img_f2022', 'img_f20', 'img_f63', 'img_f941', 'img_f921', 'img_f947', 'img_f908', 'img_f907', 'img_f929', 'img_f925', 'img_f1953', 'img_f1951', 'img_f1950', 'img_f910', 'img_f1935', 'img_f71', 'img_f1923', 'img_f55', 'img_f1911', 'img_f1966', 'img_f1928', 'img_f112', 'img_f1920', 'img_f1915', 'img_f1907', 'img_f1904', 'img_f1848', 'img_f1847', 'img_f1890', 'img_f100', 'img_f99', 'img_f1892', 'img_f139', 'img_f1880', 'img_f1879', 'img_f84', 'img_f976', 'img_f905', 'img_f902', 'img_f900', 'img_f958', 'img_f891', 'img_f887', 'img_f969', 'img_f962', 'img_f953', 'img_f951', 'img_f949', 'img_f1876', 'img_f1872', 'img_f145', 'img_f1861', 'img_f1860', 'img_f1851', 'img_f1850', 'img_f1870', 'img_f1866', 'img_f173', 'img_f1853', 'img_f158', 'img_f157', 'img_f1784', 'img_f1840', 'img_f172', 'img_f169', 'img_f1824', 'img_f1823', 'img_f155', 'img_f153', 'img_f196', 'img_f193', 'img_f1832', 'img_f1829', 'img_f1828', 'img_f1006', 'img_f1005', 'img_f876', 'img_f875', 'img_f872', 'img_f986', 'img_f982', 'img_f857', 'img_f855', 'img_f1026', 'img_f1022', 'img_f997', 'img_f993', 'img_f991', 'img_f1042', 'img_f1032', 'img_f1779', 'img_f1778', 'img_f1777', 'img_f202', 'img_f201', 'img_f1759', 'img_f1750', 'img_f192', 'img_f1794', 'img_f1770', 'img_f1764', 'img_f1812', 'img_f1803', 'img_f823', 'img_f1015', 'img_f1013', 'img_f852', 'img_f1060', 'img_f1059', 'img_f834', 'img_f830', 'img_f1048', 'img_f1046', 'img_f1072', 'img_f1063', 'img_f1062', 'img_f871', 'img_f867', 'img_f1053', 'img_f1052', 'img_f1051', 'img_f1723', 'img_f205', 'img_f203', 'img_f1736', 'img_f1734', 'img_f1733', 'img_f264', 'img_f261', 'img_f259', 'img_f1718', 'img_f212', 'img_f208', 'img_f206', 'img_f1108', 'img_f816', 'img_f814', 'img_f808', 'img_f1093', 'img_f794', 'img_f1082', 'img_f1079', 'img_f1102', 'img_f849', 'img_f845', 'img_f1085', 'img_f247', 'img_f1715', 'img_f276', 'img_f266', 'img_f1694', 'img_f252', 'img_f249', 'img_f239', 'img_f1712', 'img_f1706', 'img_f1704', 'img_f301', 'img_f296', 'img_f1688', 'img_f1687', 'img_f769', 'img_f766', 'img_f1136', 'img_f1134', 'img_f775', 'img_f774', 'img_f770', 'img_f1122', 'img_f1117', 'img_f760', 'img_f757', 'img_f799', 'img_f1131', 'img_f1130', 'img_f1128', 'img_f1126', 'img_f280', 'img_f308', 'img_f307', 'img_f305', 'img_f1678', 'img_f1677', 'img_f293', 'img_f289', 'img_f1658', 'img_f1679', 'img_f1671', 'img_f1171', 'img_f1111', 'img_f735', 'img_f729', 'img_f727', 'img_f1141', 'img_f1161', 'img_f1156', 'img_f779', 'img_f776', 'img_f1151', 'img_f1149', 'img_f1148', 'img_f322', 'img_f1601', 'img_f309', 'img_f334', 'img_f331', 'img_f328', 'img_f327', 'img_f1623', 'img_f315', 'img_f313', 'img_f310', 'img_f350', 'img_f1645', 'img_f1580', 'img_f355', 'img_f351', 'img_f1563', 'img_f1562', 'img_f1561', 'img_f341', 'img_f1584', 'img_f1581', 'img_f1607', 'img_f1606', 'img_f1575', 'img_f1574', 'img_f1571', 'img_f1570', 'img_f1560', 'img_f1615', 'img_f1202', 'img_f718', 'img_f715', 'img_f708', 'img_f1184', 'img_f1179', 'img_f696', 'img_f694', 'img_f1203', 'img_f687', 'img_f1191', 'img_f1188', 'img_f1186', 'img_f754', 'img_f1175', 'img_f692', 'img_f401', 'img_f399', 'img_f395', 'img_f1538', 'img_f384', 'img_f383', 'img_f380', 'img_f378', 'img_f377', 'img_f369', 'img_f367', 'img_f1554', 'img_f1552', 'img_f1543', 'img_f1530', 'img_f1529', 'img_f684', 'img_f1225', 'img_f670', 'img_f668', 'img_f664', 'img_f1212', 'img_f1211', 'img_f1209', 'img_f1230', 'img_f1228', 'img_f703', 'img_f1222', 'img_f1461', 'img_f435', 'img_f434', 'img_f433', 'img_f432', 'img_f1518', 'img_f1516', 'img_f1514', 'img_f424', 'img_f1497', 'img_f408', 'img_f1522', 'img_f457', 'img_f1511', 'img_f1508', 'img_f1504', 'img_f1265', 'img_f660', 'img_f649', 'img_f1249', 'img_f1246', 'img_f640', 'img_f629', 'img_f624', 'img_f1262', 'img_f1256', 'img_f1253', 'img_f677', 'img_f673', 'img_f1241', 'img_f441', 'img_f437', 'img_f1437', 'img_f1484', 'img_f456', 'img_f455', 'img_f1464', 'img_f1490', 'img_f1487', 'img_f1398', 'img_f1472', 'img_f1469', 'img_f1287', 'img_f617', 'img_f613', 'img_f608', 'img_f1275', 'img_f1272', 'img_f599', 'img_f1294', 'img_f1319', 'img_f1280', 'img_f648', 'img_f644', 'img_f1332', 'img_f1324', 'img_f482', 'img_f481', 'img_f1409', 'img_f1405', 'img_f1402', 'img_f1454', 'img_f1447', 'img_f1445', 'img_f478', 'img_f477', 'img_f475', 'img_f1367', 'img_f1453', 'img_f1449', 'img_f520', 'img_f519', 'img_f1375', 'img_f1374', 'img_f503', 'img_f502', 'img_f1428', 'img_f1414', 'img_f517', 'img_f536', 'img_f1425', 'img_f1420', 'img_f1418', 'img_f1417', 'img_f576', 'img_f573', 'img_f1318', 'img_f1304', 'img_f565', 'img_f559', 'img_f577', 'img_f545', 'img_f572', 'img_f568', 'img_f566', 'img_f604', 'img_f555', 'img_f1359', 'img_f1358', 'img_f539', 'img_f1363', 'img_f1390', 'img_f1384', 'img_f1353', 'img_f1346', 'img_f590', 'img_f589', 'img_f1333', 'img_f1395', 'img_f1393', 'temp_low', 'img_f2046', 'Heat_D-D', 'Temp_Out', 'img_f2044', 'img_f2013', 'img_f2010', 'img_f24', 'img_f1955', 'img_f1983', 'img_f1982', 'img_f50', 'img_f43', 'img_f41', 'img_f2033', 'img_f2032', 'img_f2030', 'img_f2004', 'img_f1993', 'img_f1992', 'img_f1990', 'img_f1981', 'img_f1978', 'img_f414', 'img_f1456', 'img_f1351', 'img_f554', 'img_f1894', 'img_f863', 'img_f1780', 'img_f243', 'img_f101', 'img_f1836', 'img_f1867', 'img_f59', 'img_f679', 'img_f1419', 'class_label_encoded']

String columns
['class_label', 'wind_dir', 'season']

String columns with unique counts
class_label: unique=4, avg_len=9.81
wind_dir: unique=9, avg_len=2.35
season: unique=3, avg_len=6.00

Target column
class_label_encoded

Input categorical columns
['wind_dir', 'season']

Final columns after one-hot encoding

In [23]:
import pandas as pd

df = df_reduced_val.copy()


label_map = {
    "FRESH": 0,
    "BLOAT": 1,
    "ACTIVE_DECAY": 2,
    "ADVANCED_DECAY": 3
}
df["class_label_encoded"] = df["class_label"].map(label_map)

# check mapping
print("Encoded target preview")
print(df[["class_label", "class_label_encoded"]].drop_duplicates())


numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
string_cols = df.select_dtypes(include=["object", "string"]).columns.tolist()


print("\nNumeric columns")
print(numeric_cols)

print("\nString columns")
print(string_cols)


print("\nString columns with unique counts")
for col in string_cols:
    print(f"{col}: unique={df[col].nunique(dropna=True)}, avg_len={df[col].astype(str).str.len().mean():.2f}")

target_col = "class_label_encoded"
raw_target_col = "class_label"


# input categorical columns only
categorical_cols = ["wind_dir", "season"]
categorical_cols = [c for c in categorical_cols if c in df.columns]

print("\nTarget column")
print(target_col)

print("\nInput categorical columns")
print(categorical_cols)


df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
df_encoded = df_encoded.drop(columns=[raw_target_col], errors="ignore")

print("\nFinal columns after one-hot encoding")
print(df_encoded.columns.tolist())

print("\nFinal shape")
print(df_encoded.shape)

df_encoded.to_csv("./metadata_split/val_processed_data.csv", index=False)
print("\nSaved to val processed_data.csv")

Encoded target preview
        class_label  class_label_encoded
0             FRESH                    0
18            BLOAT                    1
62     ACTIVE_DECAY                    2
101  ADVANCED_DECAY                    3

Numeric columns
['year', 'img_f397', 'img_f492', 'img_f339', 'img_f392', 'img_f142', 'img_f311', 'img_f743', 'img_f888', 'img_f1947', 'img_f1763', 'img_f1123', 'img_f1806', 'img_f1713', 'img_f1549', 'img_f1260', 'img_f1105', 'img_f1018', 'img_f27', 'img_f38', 'img_f840', 'img_f1639', 'img_f92', 'img_f764', 'img_f14', 'img_f1170', 'img_f496', 'img_f717', 'img_f879', 'img_f558', 'img_f1871', 'img_f1133', 'img_f994', 'img_f335', 'img_f1309', 'img_f1271', 'img_f809', 'img_f2047', 'img_f987', 'img_f30', 'img_f1373', 'img_f1458', 'img_f58', 'img_f1295', 'img_f1625', 'img_f1243', 'img_f674', 'img_f246', 'img_f1998', 'img_f744', 'img_f1501', 'img_f657', 'img_f898', 'img_f974', 'img_f1924', 'img_f1881', 'img_f211', 'img_f931', 'img_f1411', 'img_f1204', 'img_f93', 'img_f2042', 'img_f410', 'img_f1985', 'img_f1572', 'img_f379', 'img_f21', 'img_f459', 'img_f798', 'img_f1635', 'img_f1391', 'img_f1199', 'img_f248', 'img_f1016', 'img_f1423', 'img_f1000', 'img_f1457', 'img_f88', 'img_f175', 'img_f926', 'img_f753', 'img_f250', 'img_f1388', 'img_f370', 'img_f357', 'img_f1844', 'img_f446', 'img_f1805', 'img_f1327', 'img_f324', 'img_f1696', 'img_f1014', 'img_f1281', 'img_f1611', 'img_f104', 'img_f667', 'img_f531', 'img_f683', 'img_f1542', 'img_f886', 'img_f826', 'img_f1975', 'img_f1721', 'img_f1350', 'img_f903', 'img_f1648', 'img_f1320', 'img_f1555', 'img_f1599', 'img_f1995', 'img_f279', 'img_f1408', 'img_f746', 'img_f1477', 'img_f1800', 'img_f1808', 'img_f513', 'img_f1944', 'img_f1394', 'img_f833', 'img_f541', 'img_f1732', 'img_f1854', 'img_f600', 'img_f1030', 'img_f1058', 'img_f2017', 'img_f381', 'img_f922', 'img_f1368', 'img_f1502', 'img_f851', 'img_f1113', 'img_f1041', 'img_f942', 'img_f215', 'img_f234', 'img_f1444', 'img_f647', 'img_f1426', 'img_f990', 'img_f693', 'img_f15', 'img_f935', 'img_f1168', 'img_f1242', 'img_f1167', 'img_f984', 'img_f26', 'img_f756', 'img_f179', 'img_f741', 'img_f1865', 'img_f1943', 'img_f1942', 'img_f1342', 'img_f151', 'img_f29', 'img_f1567', 'img_f507', 'img_f241', 'img_f1910', 'img_f60', 'img_f2031', 'img_f817', 'img_f1049', 'img_f1968', 'img_f981', 'img_f1546', 'img_f91', 'img_f323', 'img_f701', 'img_f1205', 'img_f1716', 'img_f1843', 'img_f1071', 'img_f1107', 'img_f1463', 'img_f1752', 'img_f1946', 'img_f1864', 'img_f1631', 'img_f1165', 'img_f788', 'img_f1901', 'img_f1905', 'img_f745', 'img_f1667', 'img_f469', 'img_f36', 'img_f2002', 'img_f999', 'img_f1331', 'img_f1238', 'img_f1307', 'img_f580', 'img_f1355', 'img_f1068', 'img_f1382', 'img_f1972', 'img_f1509', 'img_f398', 'img_f134', 'img_f1337', 'img_f528', 'img_f697', 'img_f1379', 'img_f1691', 'img_f839', 'img_f847', 'img_f723', 'img_f725', 'img_f1479', 'img_f1442', 'img_f282', 'img_f445', 'img_f438', 'img_f1566', 'img_f1613', 'img_f1994', 'img_f966', 'img_f1403', 'img_f125', 'img_f116', 'img_f114', 'img_f1616', 'img_f238', 'img_f1700', 'img_f97', 'img_f1178', 'img_f526', 'img_f42', 'img_f1038', 'img_f1034', 'img_f1027', 'img_f1819', 'img_f1480', 'img_f767', 'img_f636', 'img_f1971', 'img_f52', 'img_f1347', 'img_f1142', 'img_f1967', 'img_f1916', 'img_f1893', 'img_f1877', 'img_f304', 'img_f1356', 'img_f593', 'img_f1308', 'img_f236', 'img_f242', 'img_f220', 'img_f183', 'img_f1641', 'img_f810', 'img_f1078', 'img_f1301', 'img_f5', 'img_f18', 'Wind_Run', 'img_f911', 'img_f890', 'img_f1551', 'img_f1534', 'img_f1545', 'img_f368', 'img_f364', 'img_f1973', 'img_f1535', 'img_f1001', 'img_f721', 'img_f353', 'img_f1588', 'img_f1558', 'img_f2023', 'img_f1596', 'img_f385', 'img_f396', 'img_f1478', 'img_f422', 'img_f1640', 'img_f835', 'img_f1076', 'img_f1315', 'img_f1303', 'img_f581', 'img_f219', 'img_f224', 'img_f1719', 'img_f1729', 'img_f1727', 'img_f557', 'img_f564', 'img_f49', 'img_f1248', 'img_f1244', 'img_f616', 'img_f1270', 'img_f1291', 'img_f300', 'img_f1139', 'img_f759', 'img_f1785', 'img_f630', 'img_f650', 'img_f1267', 'img_f1949', 'img_f758', 'img_f1120', 'img_f1821', 'img_f144', 'img_f698', 'img_f1214', 'img_f659', 'img_f1799', 'img_f988', 'img_f781', 'img_f94', 'img_f1192', 'img_f1201', 'img_f532', 'img_f515', 'img_f245', 'img_f262', 'img_f269', 'img_f1158', 'img_f1415', 'img_f494', 'img_f1404', 'img_f132', 'img_f390', 'img_f28', 'img_f7', 'img_f358', 'img_f747', 'img_f1164', 'img_f1064', 'img_f818', 'img_f789', 'img_f1751', 'img_f1330', 'img_f405', 'img_f1525', 'img_f2001', 'img_f1980', 'img_f1789', 'img_f1595', 'img_f320', 'img_f317', 'img_f394', 'img_f342', 'img_f354', 'img_f933', 'img_f752', 'img_f129', 'img_f126', 'img_f140', 'img_f1400', 'img_f499', 'img_f497', 'img_f281', 'img_f272', 'img_f1439', 'img_f1460', 'img_f452', 'img_f449', 'img_f512', 'img_f254', 'img_f251', 'img_f1699', 'img_f1702', 'img_f1173', 'img_f518', 'img_f1100', 'img_f1081', 'img_f89', 'img_f1834', 'img_f1817', 'img_f1814', 'img_f705', 'img_f1896', 'img_f78', 'img_f1883', 'img_f1127', 'img_f1121', 'img_f53', 'img_f1909', 'img_f1965', 'img_f1361', 'img_f1338', 'img_f1147', 'img_f150', 'img_f149', 'img_f1822', 'img_f1726', 'img_f556', 'img_f585', 'img_f218', 'img_f1765', 'img_f1047', 'img_f1492', 'img_f444', 'img_f1473', 'img_f413', 'img_f194', 'img_f189', 'img_f209', 'img_f1774', 'img_f186', 'img_f1772', 'img_f1769', 'img_f303', 'img_f418', 'img_f415', 'img_f1512', 'img_f1506', 'img_f633', 'img_f612', 'img_f1284', 'img_f1505', 'img_f983', 'img_f1959', 'img_f1948', 'img_f1792', 'img_f652', 'img_f651', 'img_f846', 'img_f1500', 'img_f1608', 'img_f2011', 'img_f1219', 'img_f1226', 'img_f658', 'img_f2014', 'img_f856', 'img_f854', 'img_f1003', 'img_f352', 'img_f345', 'img_f1528', 'img_f862', 'img_f1536', 'img_f13', 'img_f9', 'img_f1868', 'img_f107', 'img_f105', 'img_f733', 'img_f505', 'img_f2027', 'img_f2028', 'img_f939', 'img_f928', 'img_f917', 'img_f1802', 'img_f1811', 'img_f170', 'img_f162', 'img_f166', 'img_f174', 'img_f1788', 'img_f632', 'img_f1804', 'img_f1268', 'img_f1180', 'img_f583', 'img_f675', 'img_f671', 'img_f1176', 'img_f1187', 'img_f1181', 'img_f822', 'img_f45', 'img_f1941', 'img_f31', 'img_f827', 'img_f40', 'img_f51', 'img_f47', 'img_f1036', 'img_f1954', 'img_f1614', 'img_f403', 'img_f1011', 'img_f591', 'img_f1299', 'img_f610', 'img_f595', 'img_f1236', 'img_f1809', 'img_f1755', 'img_f614', 'img_f1285', 'img_f1813', 'img_f1498', 'img_f1503', 'img_f465', 'img_f409', 'img_f463', 'img_f1481', 'img_f299', 'img_f1544', 'img_f373', 'img_f330', 'img_f329', 'img_f325', 'img_f295', 'img_f1510', 'img_f1521', 'img_f1630', 'img_f548', 'img_f550', 'img_f561', 'img_f1766', 'img_f1775', 'img_f1758', 'img_f1757', 'img_f188', 'img_f185', 'img_f1753', 'img_f700', 'img_f1845', 'img_f1859', 'img_f736', 'img_f1657', 'img_f1446', 'img_f1662', 'img_f273', 'img_f1092', 'img_f1106', 'img_f1103', 'img_f804', 'img_f79', 'img_f400', 'img_f54', 'img_f67', 'img_f64', 'img_f510', 'img_f530', 'img_f1701', 'img_f111', 'img_f229', 'img_f737', 'img_f1743', 'img_f567', 'img_f1118', 'img_f1906', 'img_f1903', 'img_f772', 'img_f1152', 'img_f500', 'img_f495', 'img_f277', 'img_f501', 'img_f516', 'img_f1349', 'img_f288', 'img_f286', 'img_f1392', 'img_f1432', 'img_f1376', 'img_f1387', 'img_f1383', 'img_f1381', 'img_f1429', 'img_f1440', 'img_f473', 'img_f472', 'img_f471', 'img_f127', 'img_f138', 'img_f508', 'img_f1698', 'img_f1116', 'img_f813', 'img_f1056', 'img_f807', 'img_f820', 'img_f1088', 'img_f1067', 'img_f1065', 'img_f797', 'img_f423', 'img_f1465', 'img_f1471', 'img_f1999', 'img_f1007', 'img_f2003', 'img_f34', 'img_f343', 'img_f356', 'img_f363', 'img_f959', 'img_f957', 'img_f972', 'img_f1577', 'img_f1793', 'img_f1297', 'img_f210', 'img_f1617', 'img_f971', 'img_f970', 'img_f841', 'img_f877', 'img_f964', 'img_f16', 'img_f918', 'img_f8', 'img_f1782', 'img_f1801', 'img_f160', 'img_f171', 'img_f1279', 'img_f1796', 'img_f948', 'img_f946', 'img_f3', 'img_f4', 'img_f936', 'img_f968', 'img_f1024', 'img_f1033', 'img_f1029', 'img_f843', 'img_f842', 'img_f1590', 'img_f1600', 'img_f386', 'img_f382', 'img_f318', 'img_f1618', 'img_f1791', 'img_f1298', 'img_f1296', 'img_f603', 'img_f1586', 'img_f348', 'img_f346', 'temp_high', 'img_f361', 'img_f366', 'img_f1526', 'img_f23', 'img_f2000', 'img_f1997', 'img_f884', 'img_f2029', 'img_f860', 'img_f873', 'img_f314', 'img_f1663', 'img_f1462', 'img_f1482', 'img_f1650', 'img_f1649', 'img_f1090', 'img_f812', 'img_f751', 'img_f750', 'img_f1114', 'img_f819', 'img_f1138', 'img_f761', 'img_f1422', 'img_f484', 'img_f1708', 'img_f1438', 'img_f470', 'img_f263', 'img_f1431', 'img_f1386', 'img_f1348', 'img_f1343', 'img_f1334', 'img_f498', 'img_f1683', 'img_f1680', 'img_f1886', 'img_f1900', 'img_f1895', 'img_f1908', 'img_f726', 'img_f738', 'img_f214', 'img_f213', 'img_f560', 'img_f231', 'img_f588', 'img_f1737', 'img_f1744', 'img_f260', 'img_f256', 'img_f268', 'img_f514', 'img_f522', 'img_f1705', 'img_f1709', 'img_f419', 'img_f1499', 'img_f62', 'img_f831', 'img_f82', 'img_f81', 'img_f1929', 'img_f1936', 'img_f784', 'img_f783', 'img_f1083', 'img_f1077', 'img_f75', 'img_f1095', 'img_f85', 'img_f778', 'img_f1455', 'img_f1675', 'img_f271', 'img_f109', 'img_f731', 'img_f122', 'img_f131', 'img_f130', 'img_f102', 'img_f1200', 'img_f707', 'img_f709', 'img_f724', 'img_f136', 'img_f135', 'img_f1189', 'img_f1316', 'img_f1749', 'img_f1776', 'img_f1740', 'img_f1357', 'img_f1621', 'img_f1629', 'img_f1643', 'img_f416', 'img_f1550', 'img_f1633', 'img_f1548', 'img_f442', 'img_f450', 'img_f454', 'img_f436', 'img_f1435', 'img_f1494', 'img_f466', 'img_f464', 'img_f1519', 'img_f538', 'img_f1818', 'img_f1825', 'img_f714', 'img_f1841', 'img_f1839', 'img_f133', 'img_f1235', 'img_f609', 'img_f607', 'img_f621', 'img_f1239', 'img_f1247', 'img_f597', 'img_f611', 'img_f594', 'img_f1306', 'img_f1302', 'img_f626', 'img_f623', 'img_f1311', 'img_f1317', 'img_f1012', 'img_f1609', 'img_f864', 'img_f1957', 'img_f992', 'img_f989', 'img_f37', 'img_f48', 'img_f1952', 'img_f1963', 'img_f1037', 'img_f44', 'img_f828', 'img_f824', 'img_f1912', 'img_f1919', 'img_f1917', 'img_f1931', 'img_f1074', 'img_f582', 'img_f1196', 'img_f665', 'img_f663', 'img_f1254', 'img_f691', 'img_f689', 'img_f638', 'img_f161', 'img_f927', 'img_f1', 'img_f1974', 'img_f2019', 'img_f945', 'img_f943', 'img_f2034', 'img_f1579', 'img_f1565', 'img_f2012', 'img_f2009', 'img_f2008', 'img_f1569', 'img_f2006', 'img_f889', 'img_f885', 'img_f2038', 'img_f2026', 'img_f2021', 'img_f919', 'img_f930', 'img_f1988', 'img_f1987', 'img_f1984', 'img_f1996', 'img_f1991', 'img_f1989', 'img_f861', 'img_f1002', 'img_f1009', 'img_f1610', 'img_f1605', 'img_f404', 'img_f333', 'img_f1592', 'img_f1591', 'img_f1958', 'img_f1021', 'img_f1035', 'img_f858', 'img_f853', 'img_f866', 'img_f865', 'img_f1004', 'img_f1624', 'img_f1523', 'img_f1969', 'img_f1075', 'img_f1073', 'img_f836', 'img_f1945', 'img_f1956', 'img_f1553', 'img_f1636', 'img_f1632', 'img_f1644', 'img_f1638', 'img_f298', 'img_f297', 'img_f1628', 'img_f1221', 'img_f1810', 'img_f1754', 'img_f645', 'img_f654', 'img_f1210', 'img_f1208', 'img_f1835', 'img_f628', 'img_f1251', 'img_f1250', 'img_f606', 'img_f620', 'img_f1300', 'img_f1216', 'img_f1224', 'img_f682', 'img_f1207', 'img_f1206', 'img_f1217', 'img_f1321', 'img_f1325', 'img_f1274', 'img_f596', 'img_f1257', 'img_f1255', 'img_f1261', 'img_f635', 'img_f1182', 'img_f662', 'img_f676', 'img_f672', 'img_f1768', 'img_f1313', 'img_f1312', 'img_f710', 'img_f1194', 'img_f1193', 'img_f1197', 'img_f695', 'img_f549', 'img_f562', 'img_f1773', 'img_f184', 'img_f195', 'img_f1273', 'img_f1761', 'img_f1771', 'img_f1827', 'img_f716', 'img_f711', 'img_f574', 'img_f1720', 'img_f1728', 'img_f1725', 'img_f1360', 'img_f1833', 'img_f1831', 'img_f152', 'img_f164', 'img_f163', 'img_f147', 'img_f146', 'img_f1815', 'img_f720', 'img_f1143', 'img_f1150', 'img_f1162', 'img_f1157', 'img_f1172', 'img_f1898', 'img_f90', 'img_f584', 'img_f1735', 'img_f1742', 'img_f1741', 'img_f570', 'img_f728', 'img_f739', 'img_f722', 'img_f730', 'img_f527', 'img_f253', 'img_f267', 'img_f228', 'img_f223', 'img_f222', 'img_f244', 'img_f1857', 'img_f1875', 'img_f1873', 'img_f123', 'img_f120', 'img_f748', 'img_f110', 'img_f732', 'img_f240', 'img_f1690', 'img_f1689', 'img_f1686', 'img_f1695', 'img_f1707', 'img_f493', 'img_f1406', 'img_f1341', 'img_f1370', 'img_f1369', 'img_f1377', 'img_f265', 'img_f1434', 'img_f1441', 'img_f1452', 'img_f1125', 'img_f490', 'img_f489', 'img_f292', 'img_f291', 'img_f290', 'img_f1389', 'img_f1345', 'img_f87', 'img_f86', 'img_f1878', 'img_f1889', 'img_f1888', 'img_f1885', 'img_f1899', 'img_f1129', 'img_f1653', 'img_f1668', 'img_f1661', 'img_f1674', 'img_f1670', 'img_f270', 'img_f1660', 'img_f1659', 'img_f806', 'img_f805', 'img_f1091', 'img_f1474', 'img_f1647', 'img_f316', 'img_f426', 'img_f421', 'img_f763', 'img_f128', 'img_f1109', 'img_f1055', 'img_f1066', 'img_f1061', 'img_f801', 'img_f811', 'img_f1413', 'img_f1427', 'img_f1424', 'img_f1421', 'img_f479', 'img_f491', 'img_f1137', 'img_f1135', 'img_f447', 'img_f431', 'img_f1467', 'img_f340', 'img_f337', 'img_f1537', 'img_f1533', 'img_f1541', 'img_f1496', 'img_f1515', 'img_f462', 'img_f461', 'img_f1436', 'img_f1489', 'img_f443', 'img_f439', 'img_f83', 'img_f1926', 'img_f56', 'img_f832', 'img_f1970', 'img_f1517', 'img_f407', 'img_f402', 'img_f1656', 'img_f1655', 'img_f476', 'img_f1097', 'img_f108', 'img_f61', 'img_f76', 'img_f73', 'img_f6', 'img_f11', 'img_f0', 'img_f2', 'img_f2039', 'img_f870', 'img_f973', 'img_f892', 'img_f955', 'img_f1564', 'img_f1557', 'img_f2020', 'img_f2007', 'img_f17', 'img_f1025', 'img_f1023', 'img_f895', 'img_f906', 'img_f904', 'img_f914', 'img_f920', 'img_f980', 'img_f1603', 'img_f1597', 'img_f1612', 'img_f1031', 'img_f1043', 'img_f1040', 'img_f844', 'img_f1017', 'img_f1790', 'img_f1783', 'img_f634', 'img_f631', 'img_f641', 'img_f639', 'img_f1245', 'img_f1258', 'wind_speed', 'img_f1293', 'img_f191', 'img_f190', 'img_f207', 'img_f1278', 'img_f1292', 'img_f1290', 'img_f880', 'img_f359', 'img_f1539', 'img_f1573', 'img_f1587', 'img_f1585', 'img_f344', 'img_f2037', 'img_f869', 'img_f1979', 'img_f1977', 'img_f1008', 'img_f963', 'img_f960', 'img_f35', 'img_f32', 'img_f2024', 'img_f2022', 'img_f20', 'img_f63', 'img_f941', 'img_f921', 'img_f947', 'img_f908', 'img_f907', 'img_f929', 'img_f925', 'img_f1953', 'img_f1951', 'img_f1950', 'img_f910', 'img_f1935', 'img_f71', 'img_f1923', 'img_f55', 'img_f1911', 'img_f1966', 'img_f1928', 'img_f112', 'img_f1920', 'img_f1915', 'img_f1907', 'img_f1904', 'img_f1848', 'img_f1847', 'img_f1890', 'img_f100', 'img_f99', 'img_f1892', 'img_f139', 'img_f1880', 'img_f1879', 'img_f84', 'img_f976', 'img_f905', 'img_f902', 'img_f900', 'img_f958', 'img_f891', 'img_f887', 'img_f969', 'img_f962', 'img_f953', 'img_f951', 'img_f949', 'img_f1876', 'img_f1872', 'img_f145', 'img_f1861', 'img_f1860', 'img_f1851', 'img_f1850', 'img_f1870', 'img_f1866', 'img_f173', 'img_f1853', 'img_f158', 'img_f157', 'img_f1784', 'img_f1840', 'img_f172', 'img_f169', 'img_f1824', 'img_f1823', 'img_f155', 'img_f153', 'img_f196', 'img_f193', 'img_f1832', 'img_f1829', 'img_f1828', 'img_f1006', 'img_f1005', 'img_f876', 'img_f875', 'img_f872', 'img_f986', 'img_f982', 'img_f857', 'img_f855', 'img_f1026', 'img_f1022', 'img_f997', 'img_f993', 'img_f991', 'img_f1042', 'img_f1032', 'img_f1779', 'img_f1778', 'img_f1777', 'img_f202', 'img_f201', 'img_f1759', 'img_f1750', 'img_f192', 'img_f1794', 'img_f1770', 'img_f1764', 'img_f1812', 'img_f1803', 'img_f823', 'img_f1015', 'img_f1013', 'img_f852', 'img_f1060', 'img_f1059', 'img_f834', 'img_f830', 'img_f1048', 'img_f1046', 'img_f1072', 'img_f1063', 'img_f1062', 'img_f871', 'img_f867', 'img_f1053', 'img_f1052', 'img_f1051', 'img_f1723', 'img_f205', 'img_f203', 'img_f1736', 'img_f1734', 'img_f1733', 'img_f264', 'img_f261', 'img_f259', 'img_f1718', 'img_f212', 'img_f208', 'img_f206', 'img_f1108', 'img_f816', 'img_f814', 'img_f808', 'img_f1093', 'img_f794', 'img_f1082', 'img_f1079', 'img_f1102', 'img_f849', 'img_f845', 'img_f1085', 'img_f247', 'img_f1715', 'img_f276', 'img_f266', 'img_f1694', 'img_f252', 'img_f249', 'img_f239', 'img_f1712', 'img_f1706', 'img_f1704', 'img_f301', 'img_f296', 'img_f1688', 'img_f1687', 'img_f769', 'img_f766', 'img_f1136', 'img_f1134', 'img_f775', 'img_f774', 'img_f770', 'img_f1122', 'img_f1117', 'img_f760', 'img_f757', 'img_f799', 'img_f1131', 'img_f1130', 'img_f1128', 'img_f1126', 'img_f280', 'img_f308', 'img_f307', 'img_f305', 'img_f1678', 'img_f1677', 'img_f293', 'img_f289', 'img_f1658', 'img_f1679', 'img_f1671', 'img_f1171', 'img_f1111', 'img_f735', 'img_f729', 'img_f727', 'img_f1141', 'img_f1161', 'img_f1156', 'img_f779', 'img_f776', 'img_f1151', 'img_f1149', 'img_f1148', 'img_f322', 'img_f1601', 'img_f309', 'img_f334', 'img_f331', 'img_f328', 'img_f327', 'img_f1623', 'img_f315', 'img_f313', 'img_f310', 'img_f350', 'img_f1645', 'img_f1580', 'img_f355', 'img_f351', 'img_f1563', 'img_f1562', 'img_f1561', 'img_f341', 'img_f1584', 'img_f1581', 'img_f1607', 'img_f1606', 'img_f1575', 'img_f1574', 'img_f1571', 'img_f1570', 'img_f1560', 'img_f1615', 'img_f1202', 'img_f718', 'img_f715', 'img_f708', 'img_f1184', 'img_f1179', 'img_f696', 'img_f694', 'img_f1203', 'img_f687', 'img_f1191', 'img_f1188', 'img_f1186', 'img_f754', 'img_f1175', 'img_f692', 'img_f401', 'img_f399', 'img_f395', 'img_f1538', 'img_f384', 'img_f383', 'img_f380', 'img_f378', 'img_f377', 'img_f369', 'img_f367', 'img_f1554', 'img_f1552', 'img_f1543', 'img_f1530', 'img_f1529', 'img_f684', 'img_f1225', 'img_f670', 'img_f668', 'img_f664', 'img_f1212', 'img_f1211', 'img_f1209', 'img_f1230', 'img_f1228', 'img_f703', 'img_f1222', 'img_f1461', 'img_f435', 'img_f434', 'img_f433', 'img_f432', 'img_f1518', 'img_f1516', 'img_f1514', 'img_f424', 'img_f1497', 'img_f408', 'img_f1522', 'img_f457', 'img_f1511', 'img_f1508', 'img_f1504', 'img_f1265', 'img_f660', 'img_f649', 'img_f1249', 'img_f1246', 'img_f640', 'img_f629', 'img_f624', 'img_f1262', 'img_f1256', 'img_f1253', 'img_f677', 'img_f673', 'img_f1241', 'img_f441', 'img_f437', 'img_f1437', 'img_f1484', 'img_f456', 'img_f455', 'img_f1464', 'img_f1490', 'img_f1487', 'img_f1398', 'img_f1472', 'img_f1469', 'img_f1287', 'img_f617', 'img_f613', 'img_f608', 'img_f1275', 'img_f1272', 'img_f599', 'img_f1294', 'img_f1319', 'img_f1280', 'img_f648', 'img_f644', 'img_f1332', 'img_f1324', 'img_f482', 'img_f481', 'img_f1409', 'img_f1405', 'img_f1402', 'img_f1454', 'img_f1447', 'img_f1445', 'img_f478', 'img_f477', 'img_f475', 'img_f1367', 'img_f1453', 'img_f1449', 'img_f520', 'img_f519', 'img_f1375', 'img_f1374', 'img_f503', 'img_f502', 'img_f1428', 'img_f1414', 'img_f517', 'img_f536', 'img_f1425', 'img_f1420', 'img_f1418', 'img_f1417', 'img_f576', 'img_f573', 'img_f1318', 'img_f1304', 'img_f565', 'img_f559', 'img_f577', 'img_f545', 'img_f572', 'img_f568', 'img_f566', 'img_f604', 'img_f555', 'img_f1359', 'img_f1358', 'img_f539', 'img_f1363', 'img_f1390', 'img_f1384', 'img_f1353', 'img_f1346', 'img_f590', 'img_f589', 'img_f1333', 'img_f1395', 'img_f1393', 'temp_low', 'img_f2046', 'Heat_D-D', 'Temp_Out', 'img_f2044', 'img_f2013', 'img_f2010', 'img_f24', 'img_f1955', 'img_f1983', 'img_f1982', 'img_f50', 'img_f43', 'img_f41', 'img_f2033', 'img_f2032', 'img_f2030', 'img_f2004', 'img_f1993', 'img_f1992', 'img_f1990', 'img_f1981', 'img_f1978', 'img_f414', 'img_f1456', 'img_f1351', 'img_f554', 'img_f1894', 'img_f863', 'img_f1780', 'img_f243', 'img_f101', 'img_f1836', 'img_f1867', 'img_f59', 'img_f679', 'img_f1419', 'class_label_encoded']

String columns
['class_label', 'wind_dir', 'season']

String columns with unique counts
class_label: unique=4, avg_len=9.61
wind_dir: unique=7, avg_len=2.67
season: unique=2, avg_len=5.98

Target column
class_label_encoded

Input categorical columns
['wind_dir', 'season']

Final columns after one-hot encoding

In [24]:
import pandas as pd

df = df_reduced_test.copy()


label_map = {
    "FRESH": 0,
    "BLOAT": 1,
    "ACTIVE_DECAY": 2,
    "ADVANCED_DECAY": 3
}
df["class_label_encoded"] = df["class_label"].map(label_map)

# check mapping
print("Encoded target preview")
print(df[["class_label", "class_label_encoded"]].drop_duplicates())


numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
string_cols = df.select_dtypes(include=["object", "string"]).columns.tolist()


print("\nNumeric columns")
print(numeric_cols)

print("\nString columns")
print(string_cols)


print("\nString columns with unique counts")
for col in string_cols:
    print(f"{col}: unique={df[col].nunique(dropna=True)}, avg_len={df[col].astype(str).str.len().mean():.2f}")

target_col = "class_label_encoded"
raw_target_col = "class_label"


# input categorical columns only
categorical_cols = ["wind_dir", "season"]
categorical_cols = [c for c in categorical_cols if c in df.columns]

print("\nTarget column")
print(target_col)

print("\nInput categorical columns")
print(categorical_cols)


df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=False)
df_encoded = df_encoded.drop(columns=[raw_target_col], errors="ignore")

print("\nFinal columns after one-hot encoding")
print(df_encoded.columns.tolist())

print("\nFinal shape")
print(df_encoded.shape)

df_encoded.to_csv("./metadata_split/test_processed_data.csv", index=False)
print("\nSaved to test processed_data.csv")

Encoded target preview
       class_label  class_label_encoded
0            FRESH                    0
15           BLOAT                    1
49    ACTIVE_DECAY                    2
86  ADVANCED_DECAY                    3

Numeric columns
['year', 'img_f397', 'img_f492', 'img_f339', 'img_f392', 'img_f142', 'img_f311', 'img_f743', 'img_f888', 'img_f1947', 'img_f1763', 'img_f1123', 'img_f1806', 'img_f1713', 'img_f1549', 'img_f1260', 'img_f1105', 'img_f1018', 'img_f27', 'img_f38', 'img_f840', 'img_f1639', 'img_f92', 'img_f764', 'img_f14', 'img_f1170', 'img_f496', 'img_f717', 'img_f879', 'img_f558', 'img_f1871', 'img_f1133', 'img_f994', 'img_f335', 'img_f1309', 'img_f1271', 'img_f809', 'img_f2047', 'img_f987', 'img_f30', 'img_f1373', 'img_f1458', 'img_f58', 'img_f1295', 'img_f1625', 'img_f1243', 'img_f674', 'img_f246', 'img_f1998', 'img_f744', 'img_f1501', 'img_f657', 'img_f898', 'img_f974', 'img_f1924', 'img_f1881', 'img_f211', 'img_f931', 'img_f1411', 'img_f1204', 'img_f93', 'img_f2042', 'img_f410', 'img_f1985', 'img_f1572', 'img_f379', 'img_f21', 'img_f459', 'img_f798', 'img_f1635', 'img_f1391', 'img_f1199', 'img_f248', 'img_f1016', 'img_f1423', 'img_f1000', 'img_f1457', 'img_f88', 'img_f175', 'img_f926', 'img_f753', 'img_f250', 'img_f1388', 'img_f370', 'img_f357', 'img_f1844', 'img_f446', 'img_f1805', 'img_f1327', 'img_f324', 'img_f1696', 'img_f1014', 'img_f1281', 'img_f1611', 'img_f104', 'img_f667', 'img_f531', 'img_f683', 'img_f1542', 'img_f886', 'img_f826', 'img_f1975', 'img_f1721', 'img_f1350', 'img_f903', 'img_f1648', 'img_f1320', 'img_f1555', 'img_f1599', 'img_f1995', 'img_f279', 'img_f1408', 'img_f746', 'img_f1477', 'img_f1800', 'img_f1808', 'img_f513', 'img_f1944', 'img_f1394', 'img_f833', 'img_f541', 'img_f1732', 'img_f1854', 'img_f600', 'img_f1030', 'img_f1058', 'img_f2017', 'img_f381', 'img_f922', 'img_f1368', 'img_f1502', 'img_f851', 'img_f1113', 'img_f1041', 'img_f942', 'img_f215', 'img_f234', 'img_f1444', 'img_f647', 'img_f1426', 'img_f990', 'img_f693', 'img_f15', 'img_f935', 'img_f1168', 'img_f1242', 'img_f1167', 'img_f984', 'img_f26', 'img_f756', 'img_f179', 'img_f741', 'img_f1865', 'img_f1943', 'img_f1942', 'img_f1342', 'img_f151', 'img_f29', 'img_f1567', 'img_f507', 'img_f241', 'img_f1910', 'img_f60', 'img_f2031', 'img_f817', 'img_f1049', 'img_f1968', 'img_f981', 'img_f1546', 'img_f91', 'img_f323', 'img_f701', 'img_f1205', 'img_f1716', 'img_f1843', 'img_f1071', 'img_f1107', 'img_f1463', 'img_f1752', 'img_f1946', 'img_f1864', 'img_f1631', 'img_f1165', 'img_f788', 'img_f1901', 'img_f1905', 'img_f745', 'img_f1667', 'img_f469', 'img_f36', 'img_f2002', 'img_f999', 'img_f1331', 'img_f1238', 'img_f1307', 'img_f580', 'img_f1355', 'img_f1068', 'img_f1382', 'img_f1972', 'img_f1509', 'img_f398', 'img_f134', 'img_f1337', 'img_f528', 'img_f697', 'img_f1379', 'img_f1691', 'img_f839', 'img_f847', 'img_f723', 'img_f725', 'img_f1479', 'img_f1442', 'img_f282', 'img_f445', 'img_f438', 'img_f1566', 'img_f1613', 'img_f1994', 'img_f966', 'img_f1403', 'img_f125', 'img_f116', 'img_f114', 'img_f1616', 'img_f238', 'img_f1700', 'img_f97', 'img_f1178', 'img_f526', 'img_f42', 'img_f1038', 'img_f1034', 'img_f1027', 'img_f1819', 'img_f1480', 'img_f767', 'img_f636', 'img_f1971', 'img_f52', 'img_f1347', 'img_f1142', 'img_f1967', 'img_f1916', 'img_f1893', 'img_f1877', 'img_f304', 'img_f1356', 'img_f593', 'img_f1308', 'img_f236', 'img_f242', 'img_f220', 'img_f183', 'img_f1641', 'img_f810', 'img_f1078', 'img_f1301', 'img_f5', 'img_f18', 'Wind_Run', 'img_f911', 'img_f890', 'img_f1551', 'img_f1534', 'img_f1545', 'img_f368', 'img_f364', 'img_f1973', 'img_f1535', 'img_f1001', 'img_f721', 'img_f353', 'img_f1588', 'img_f1558', 'img_f2023', 'img_f1596', 'img_f385', 'img_f396', 'img_f1478', 'img_f422', 'img_f1640', 'img_f835', 'img_f1076', 'img_f1315', 'img_f1303', 'img_f581', 'img_f219', 'img_f224', 'img_f1719', 'img_f1729', 'img_f1727', 'img_f557', 'img_f564', 'img_f49', 'img_f1248', 'img_f1244', 'img_f616', 'img_f1270', 'img_f1291', 'img_f300', 'img_f1139', 'img_f759', 'img_f1785', 'img_f630', 'img_f650', 'img_f1267', 'img_f1949', 'img_f758', 'img_f1120', 'img_f1821', 'img_f144', 'img_f698', 'img_f1214', 'img_f659', 'img_f1799', 'img_f988', 'img_f781', 'img_f94', 'img_f1192', 'img_f1201', 'img_f532', 'img_f515', 'img_f245', 'img_f262', 'img_f269', 'img_f1158', 'img_f1415', 'img_f494', 'img_f1404', 'img_f132', 'img_f390', 'img_f28', 'img_f7', 'img_f358', 'img_f747', 'img_f1164', 'img_f1064', 'img_f818', 'img_f789', 'img_f1751', 'img_f1330', 'img_f405', 'img_f1525', 'img_f2001', 'img_f1980', 'img_f1789', 'img_f1595', 'img_f320', 'img_f317', 'img_f394', 'img_f342', 'img_f354', 'img_f933', 'img_f752', 'img_f129', 'img_f126', 'img_f140', 'img_f1400', 'img_f499', 'img_f497', 'img_f281', 'img_f272', 'img_f1439', 'img_f1460', 'img_f452', 'img_f449', 'img_f512', 'img_f254', 'img_f251', 'img_f1699', 'img_f1702', 'img_f1173', 'img_f518', 'img_f1100', 'img_f1081', 'img_f89', 'img_f1834', 'img_f1817', 'img_f1814', 'img_f705', 'img_f1896', 'img_f78', 'img_f1883', 'img_f1127', 'img_f1121', 'img_f53', 'img_f1909', 'img_f1965', 'img_f1361', 'img_f1338', 'img_f1147', 'img_f150', 'img_f149', 'img_f1822', 'img_f1726', 'img_f556', 'img_f585', 'img_f218', 'img_f1765', 'img_f1047', 'img_f1492', 'img_f444', 'img_f1473', 'img_f413', 'img_f194', 'img_f189', 'img_f209', 'img_f1774', 'img_f186', 'img_f1772', 'img_f1769', 'img_f303', 'img_f418', 'img_f415', 'img_f1512', 'img_f1506', 'img_f633', 'img_f612', 'img_f1284', 'img_f1505', 'img_f983', 'img_f1959', 'img_f1948', 'img_f1792', 'img_f652', 'img_f651', 'img_f846', 'img_f1500', 'img_f1608', 'img_f2011', 'img_f1219', 'img_f1226', 'img_f658', 'img_f2014', 'img_f856', 'img_f854', 'img_f1003', 'img_f352', 'img_f345', 'img_f1528', 'img_f862', 'img_f1536', 'img_f13', 'img_f9', 'img_f1868', 'img_f107', 'img_f105', 'img_f733', 'img_f505', 'img_f2027', 'img_f2028', 'img_f939', 'img_f928', 'img_f917', 'img_f1802', 'img_f1811', 'img_f170', 'img_f162', 'img_f166', 'img_f174', 'img_f1788', 'img_f632', 'img_f1804', 'img_f1268', 'img_f1180', 'img_f583', 'img_f675', 'img_f671', 'img_f1176', 'img_f1187', 'img_f1181', 'img_f822', 'img_f45', 'img_f1941', 'img_f31', 'img_f827', 'img_f40', 'img_f51', 'img_f47', 'img_f1036', 'img_f1954', 'img_f1614', 'img_f403', 'img_f1011', 'img_f591', 'img_f1299', 'img_f610', 'img_f595', 'img_f1236', 'img_f1809', 'img_f1755', 'img_f614', 'img_f1285', 'img_f1813', 'img_f1498', 'img_f1503', 'img_f465', 'img_f409', 'img_f463', 'img_f1481', 'img_f299', 'img_f1544', 'img_f373', 'img_f330', 'img_f329', 'img_f325', 'img_f295', 'img_f1510', 'img_f1521', 'img_f1630', 'img_f548', 'img_f550', 'img_f561', 'img_f1766', 'img_f1775', 'img_f1758', 'img_f1757', 'img_f188', 'img_f185', 'img_f1753', 'img_f700', 'img_f1845', 'img_f1859', 'img_f736', 'img_f1657', 'img_f1446', 'img_f1662', 'img_f273', 'img_f1092', 'img_f1106', 'img_f1103', 'img_f804', 'img_f79', 'img_f400', 'img_f54', 'img_f67', 'img_f64', 'img_f510', 'img_f530', 'img_f1701', 'img_f111', 'img_f229', 'img_f737', 'img_f1743', 'img_f567', 'img_f1118', 'img_f1906', 'img_f1903', 'img_f772', 'img_f1152', 'img_f500', 'img_f495', 'img_f277', 'img_f501', 'img_f516', 'img_f1349', 'img_f288', 'img_f286', 'img_f1392', 'img_f1432', 'img_f1376', 'img_f1387', 'img_f1383', 'img_f1381', 'img_f1429', 'img_f1440', 'img_f473', 'img_f472', 'img_f471', 'img_f127', 'img_f138', 'img_f508', 'img_f1698', 'img_f1116', 'img_f813', 'img_f1056', 'img_f807', 'img_f820', 'img_f1088', 'img_f1067', 'img_f1065', 'img_f797', 'img_f423', 'img_f1465', 'img_f1471', 'img_f1999', 'img_f1007', 'img_f2003', 'img_f34', 'img_f343', 'img_f356', 'img_f363', 'img_f959', 'img_f957', 'img_f972', 'img_f1577', 'img_f1793', 'img_f1297', 'img_f210', 'img_f1617', 'img_f971', 'img_f970', 'img_f841', 'img_f877', 'img_f964', 'img_f16', 'img_f918', 'img_f8', 'img_f1782', 'img_f1801', 'img_f160', 'img_f171', 'img_f1279', 'img_f1796', 'img_f948', 'img_f946', 'img_f3', 'img_f4', 'img_f936', 'img_f968', 'img_f1024', 'img_f1033', 'img_f1029', 'img_f843', 'img_f842', 'img_f1590', 'img_f1600', 'img_f386', 'img_f382', 'img_f318', 'img_f1618', 'img_f1791', 'img_f1298', 'img_f1296', 'img_f603', 'img_f1586', 'img_f348', 'img_f346', 'temp_high', 'img_f361', 'img_f366', 'img_f1526', 'img_f23', 'img_f2000', 'img_f1997', 'img_f884', 'img_f2029', 'img_f860', 'img_f873', 'img_f314', 'img_f1663', 'img_f1462', 'img_f1482', 'img_f1650', 'img_f1649', 'img_f1090', 'img_f812', 'img_f751', 'img_f750', 'img_f1114', 'img_f819', 'img_f1138', 'img_f761', 'img_f1422', 'img_f484', 'img_f1708', 'img_f1438', 'img_f470', 'img_f263', 'img_f1431', 'img_f1386', 'img_f1348', 'img_f1343', 'img_f1334', 'img_f498', 'img_f1683', 'img_f1680', 'img_f1886', 'img_f1900', 'img_f1895', 'img_f1908', 'img_f726', 'img_f738', 'img_f214', 'img_f213', 'img_f560', 'img_f231', 'img_f588', 'img_f1737', 'img_f1744', 'img_f260', 'img_f256', 'img_f268', 'img_f514', 'img_f522', 'img_f1705', 'img_f1709', 'img_f419', 'img_f1499', 'img_f62', 'img_f831', 'img_f82', 'img_f81', 'img_f1929', 'img_f1936', 'img_f784', 'img_f783', 'img_f1083', 'img_f1077', 'img_f75', 'img_f1095', 'img_f85', 'img_f778', 'img_f1455', 'img_f1675', 'img_f271', 'img_f109', 'img_f731', 'img_f122', 'img_f131', 'img_f130', 'img_f102', 'img_f1200', 'img_f707', 'img_f709', 'img_f724', 'img_f136', 'img_f135', 'img_f1189', 'img_f1316', 'img_f1749', 'img_f1776', 'img_f1740', 'img_f1357', 'img_f1621', 'img_f1629', 'img_f1643', 'img_f416', 'img_f1550', 'img_f1633', 'img_f1548', 'img_f442', 'img_f450', 'img_f454', 'img_f436', 'img_f1435', 'img_f1494', 'img_f466', 'img_f464', 'img_f1519', 'img_f538', 'img_f1818', 'img_f1825', 'img_f714', 'img_f1841', 'img_f1839', 'img_f133', 'img_f1235', 'img_f609', 'img_f607', 'img_f621', 'img_f1239', 'img_f1247', 'img_f597', 'img_f611', 'img_f594', 'img_f1306', 'img_f1302', 'img_f626', 'img_f623', 'img_f1311', 'img_f1317', 'img_f1012', 'img_f1609', 'img_f864', 'img_f1957', 'img_f992', 'img_f989', 'img_f37', 'img_f48', 'img_f1952', 'img_f1963', 'img_f1037', 'img_f44', 'img_f828', 'img_f824', 'img_f1912', 'img_f1919', 'img_f1917', 'img_f1931', 'img_f1074', 'img_f582', 'img_f1196', 'img_f665', 'img_f663', 'img_f1254', 'img_f691', 'img_f689', 'img_f638', 'img_f161', 'img_f927', 'img_f1', 'img_f1974', 'img_f2019', 'img_f945', 'img_f943', 'img_f2034', 'img_f1579', 'img_f1565', 'img_f2012', 'img_f2009', 'img_f2008', 'img_f1569', 'img_f2006', 'img_f889', 'img_f885', 'img_f2038', 'img_f2026', 'img_f2021', 'img_f919', 'img_f930', 'img_f1988', 'img_f1987', 'img_f1984', 'img_f1996', 'img_f1991', 'img_f1989', 'img_f861', 'img_f1002', 'img_f1009', 'img_f1610', 'img_f1605', 'img_f404', 'img_f333', 'img_f1592', 'img_f1591', 'img_f1958', 'img_f1021', 'img_f1035', 'img_f858', 'img_f853', 'img_f866', 'img_f865', 'img_f1004', 'img_f1624', 'img_f1523', 'img_f1969', 'img_f1075', 'img_f1073', 'img_f836', 'img_f1945', 'img_f1956', 'img_f1553', 'img_f1636', 'img_f1632', 'img_f1644', 'img_f1638', 'img_f298', 'img_f297', 'img_f1628', 'img_f1221', 'img_f1810', 'img_f1754', 'img_f645', 'img_f654', 'img_f1210', 'img_f1208', 'img_f1835', 'img_f628', 'img_f1251', 'img_f1250', 'img_f606', 'img_f620', 'img_f1300', 'img_f1216', 'img_f1224', 'img_f682', 'img_f1207', 'img_f1206', 'img_f1217', 'img_f1321', 'img_f1325', 'img_f1274', 'img_f596', 'img_f1257', 'img_f1255', 'img_f1261', 'img_f635', 'img_f1182', 'img_f662', 'img_f676', 'img_f672', 'img_f1768', 'img_f1313', 'img_f1312', 'img_f710', 'img_f1194', 'img_f1193', 'img_f1197', 'img_f695', 'img_f549', 'img_f562', 'img_f1773', 'img_f184', 'img_f195', 'img_f1273', 'img_f1761', 'img_f1771', 'img_f1827', 'img_f716', 'img_f711', 'img_f574', 'img_f1720', 'img_f1728', 'img_f1725', 'img_f1360', 'img_f1833', 'img_f1831', 'img_f152', 'img_f164', 'img_f163', 'img_f147', 'img_f146', 'img_f1815', 'img_f720', 'img_f1143', 'img_f1150', 'img_f1162', 'img_f1157', 'img_f1172', 'img_f1898', 'img_f90', 'img_f584', 'img_f1735', 'img_f1742', 'img_f1741', 'img_f570', 'img_f728', 'img_f739', 'img_f722', 'img_f730', 'img_f527', 'img_f253', 'img_f267', 'img_f228', 'img_f223', 'img_f222', 'img_f244', 'img_f1857', 'img_f1875', 'img_f1873', 'img_f123', 'img_f120', 'img_f748', 'img_f110', 'img_f732', 'img_f240', 'img_f1690', 'img_f1689', 'img_f1686', 'img_f1695', 'img_f1707', 'img_f493', 'img_f1406', 'img_f1341', 'img_f1370', 'img_f1369', 'img_f1377', 'img_f265', 'img_f1434', 'img_f1441', 'img_f1452', 'img_f1125', 'img_f490', 'img_f489', 'img_f292', 'img_f291', 'img_f290', 'img_f1389', 'img_f1345', 'img_f87', 'img_f86', 'img_f1878', 'img_f1889', 'img_f1888', 'img_f1885', 'img_f1899', 'img_f1129', 'img_f1653', 'img_f1668', 'img_f1661', 'img_f1674', 'img_f1670', 'img_f270', 'img_f1660', 'img_f1659', 'img_f806', 'img_f805', 'img_f1091', 'img_f1474', 'img_f1647', 'img_f316', 'img_f426', 'img_f421', 'img_f763', 'img_f128', 'img_f1109', 'img_f1055', 'img_f1066', 'img_f1061', 'img_f801', 'img_f811', 'img_f1413', 'img_f1427', 'img_f1424', 'img_f1421', 'img_f479', 'img_f491', 'img_f1137', 'img_f1135', 'img_f447', 'img_f431', 'img_f1467', 'img_f340', 'img_f337', 'img_f1537', 'img_f1533', 'img_f1541', 'img_f1496', 'img_f1515', 'img_f462', 'img_f461', 'img_f1436', 'img_f1489', 'img_f443', 'img_f439', 'img_f83', 'img_f1926', 'img_f56', 'img_f832', 'img_f1970', 'img_f1517', 'img_f407', 'img_f402', 'img_f1656', 'img_f1655', 'img_f476', 'img_f1097', 'img_f108', 'img_f61', 'img_f76', 'img_f73', 'img_f6', 'img_f11', 'img_f0', 'img_f2', 'img_f2039', 'img_f870', 'img_f973', 'img_f892', 'img_f955', 'img_f1564', 'img_f1557', 'img_f2020', 'img_f2007', 'img_f17', 'img_f1025', 'img_f1023', 'img_f895', 'img_f906', 'img_f904', 'img_f914', 'img_f920', 'img_f980', 'img_f1603', 'img_f1597', 'img_f1612', 'img_f1031', 'img_f1043', 'img_f1040', 'img_f844', 'img_f1017', 'img_f1790', 'img_f1783', 'img_f634', 'img_f631', 'img_f641', 'img_f639', 'img_f1245', 'img_f1258', 'wind_speed', 'img_f1293', 'img_f191', 'img_f190', 'img_f207', 'img_f1278', 'img_f1292', 'img_f1290', 'img_f880', 'img_f359', 'img_f1539', 'img_f1573', 'img_f1587', 'img_f1585', 'img_f344', 'img_f2037', 'img_f869', 'img_f1979', 'img_f1977', 'img_f1008', 'img_f963', 'img_f960', 'img_f35', 'img_f32', 'img_f2024', 'img_f2022', 'img_f20', 'img_f63', 'img_f941', 'img_f921', 'img_f947', 'img_f908', 'img_f907', 'img_f929', 'img_f925', 'img_f1953', 'img_f1951', 'img_f1950', 'img_f910', 'img_f1935', 'img_f71', 'img_f1923', 'img_f55', 'img_f1911', 'img_f1966', 'img_f1928', 'img_f112', 'img_f1920', 'img_f1915', 'img_f1907', 'img_f1904', 'img_f1848', 'img_f1847', 'img_f1890', 'img_f100', 'img_f99', 'img_f1892', 'img_f139', 'img_f1880', 'img_f1879', 'img_f84', 'img_f976', 'img_f905', 'img_f902', 'img_f900', 'img_f958', 'img_f891', 'img_f887', 'img_f969', 'img_f962', 'img_f953', 'img_f951', 'img_f949', 'img_f1876', 'img_f1872', 'img_f145', 'img_f1861', 'img_f1860', 'img_f1851', 'img_f1850', 'img_f1870', 'img_f1866', 'img_f173', 'img_f1853', 'img_f158', 'img_f157', 'img_f1784', 'img_f1840', 'img_f172', 'img_f169', 'img_f1824', 'img_f1823', 'img_f155', 'img_f153', 'img_f196', 'img_f193', 'img_f1832', 'img_f1829', 'img_f1828', 'img_f1006', 'img_f1005', 'img_f876', 'img_f875', 'img_f872', 'img_f986', 'img_f982', 'img_f857', 'img_f855', 'img_f1026', 'img_f1022', 'img_f997', 'img_f993', 'img_f991', 'img_f1042', 'img_f1032', 'img_f1779', 'img_f1778', 'img_f1777', 'img_f202', 'img_f201', 'img_f1759', 'img_f1750', 'img_f192', 'img_f1794', 'img_f1770', 'img_f1764', 'img_f1812', 'img_f1803', 'img_f823', 'img_f1015', 'img_f1013', 'img_f852', 'img_f1060', 'img_f1059', 'img_f834', 'img_f830', 'img_f1048', 'img_f1046', 'img_f1072', 'img_f1063', 'img_f1062', 'img_f871', 'img_f867', 'img_f1053', 'img_f1052', 'img_f1051', 'img_f1723', 'img_f205', 'img_f203', 'img_f1736', 'img_f1734', 'img_f1733', 'img_f264', 'img_f261', 'img_f259', 'img_f1718', 'img_f212', 'img_f208', 'img_f206', 'img_f1108', 'img_f816', 'img_f814', 'img_f808', 'img_f1093', 'img_f794', 'img_f1082', 'img_f1079', 'img_f1102', 'img_f849', 'img_f845', 'img_f1085', 'img_f247', 'img_f1715', 'img_f276', 'img_f266', 'img_f1694', 'img_f252', 'img_f249', 'img_f239', 'img_f1712', 'img_f1706', 'img_f1704', 'img_f301', 'img_f296', 'img_f1688', 'img_f1687', 'img_f769', 'img_f766', 'img_f1136', 'img_f1134', 'img_f775', 'img_f774', 'img_f770', 'img_f1122', 'img_f1117', 'img_f760', 'img_f757', 'img_f799', 'img_f1131', 'img_f1130', 'img_f1128', 'img_f1126', 'img_f280', 'img_f308', 'img_f307', 'img_f305', 'img_f1678', 'img_f1677', 'img_f293', 'img_f289', 'img_f1658', 'img_f1679', 'img_f1671', 'img_f1171', 'img_f1111', 'img_f735', 'img_f729', 'img_f727', 'img_f1141', 'img_f1161', 'img_f1156', 'img_f779', 'img_f776', 'img_f1151', 'img_f1149', 'img_f1148', 'img_f322', 'img_f1601', 'img_f309', 'img_f334', 'img_f331', 'img_f328', 'img_f327', 'img_f1623', 'img_f315', 'img_f313', 'img_f310', 'img_f350', 'img_f1645', 'img_f1580', 'img_f355', 'img_f351', 'img_f1563', 'img_f1562', 'img_f1561', 'img_f341', 'img_f1584', 'img_f1581', 'img_f1607', 'img_f1606', 'img_f1575', 'img_f1574', 'img_f1571', 'img_f1570', 'img_f1560', 'img_f1615', 'img_f1202', 'img_f718', 'img_f715', 'img_f708', 'img_f1184', 'img_f1179', 'img_f696', 'img_f694', 'img_f1203', 'img_f687', 'img_f1191', 'img_f1188', 'img_f1186', 'img_f754', 'img_f1175', 'img_f692', 'img_f401', 'img_f399', 'img_f395', 'img_f1538', 'img_f384', 'img_f383', 'img_f380', 'img_f378', 'img_f377', 'img_f369', 'img_f367', 'img_f1554', 'img_f1552', 'img_f1543', 'img_f1530', 'img_f1529', 'img_f684', 'img_f1225', 'img_f670', 'img_f668', 'img_f664', 'img_f1212', 'img_f1211', 'img_f1209', 'img_f1230', 'img_f1228', 'img_f703', 'img_f1222', 'img_f1461', 'img_f435', 'img_f434', 'img_f433', 'img_f432', 'img_f1518', 'img_f1516', 'img_f1514', 'img_f424', 'img_f1497', 'img_f408', 'img_f1522', 'img_f457', 'img_f1511', 'img_f1508', 'img_f1504', 'img_f1265', 'img_f660', 'img_f649', 'img_f1249', 'img_f1246', 'img_f640', 'img_f629', 'img_f624', 'img_f1262', 'img_f1256', 'img_f1253', 'img_f677', 'img_f673', 'img_f1241', 'img_f441', 'img_f437', 'img_f1437', 'img_f1484', 'img_f456', 'img_f455', 'img_f1464', 'img_f1490', 'img_f1487', 'img_f1398', 'img_f1472', 'img_f1469', 'img_f1287', 'img_f617', 'img_f613', 'img_f608', 'img_f1275', 'img_f1272', 'img_f599', 'img_f1294', 'img_f1319', 'img_f1280', 'img_f648', 'img_f644', 'img_f1332', 'img_f1324', 'img_f482', 'img_f481', 'img_f1409', 'img_f1405', 'img_f1402', 'img_f1454', 'img_f1447', 'img_f1445', 'img_f478', 'img_f477', 'img_f475', 'img_f1367', 'img_f1453', 'img_f1449', 'img_f520', 'img_f519', 'img_f1375', 'img_f1374', 'img_f503', 'img_f502', 'img_f1428', 'img_f1414', 'img_f517', 'img_f536', 'img_f1425', 'img_f1420', 'img_f1418', 'img_f1417', 'img_f576', 'img_f573', 'img_f1318', 'img_f1304', 'img_f565', 'img_f559', 'img_f577', 'img_f545', 'img_f572', 'img_f568', 'img_f566', 'img_f604', 'img_f555', 'img_f1359', 'img_f1358', 'img_f539', 'img_f1363', 'img_f1390', 'img_f1384', 'img_f1353', 'img_f1346', 'img_f590', 'img_f589', 'img_f1333', 'img_f1395', 'img_f1393', 'temp_low', 'img_f2046', 'Heat_D-D', 'Temp_Out', 'img_f2044', 'img_f2013', 'img_f2010', 'img_f24', 'img_f1955', 'img_f1983', 'img_f1982', 'img_f50', 'img_f43', 'img_f41', 'img_f2033', 'img_f2032', 'img_f2030', 'img_f2004', 'img_f1993', 'img_f1992', 'img_f1990', 'img_f1981', 'img_f1978', 'img_f414', 'img_f1456', 'img_f1351', 'img_f554', 'img_f1894', 'img_f863', 'img_f1780', 'img_f243', 'img_f101', 'img_f1836', 'img_f1867', 'img_f59', 'img_f679', 'img_f1419', 'class_label_encoded']

String columns
['class_label', 'wind_dir', 'season']

String columns with unique counts
class_label: unique=4, avg_len=10.50
wind_dir: unique=6, avg_len=2.67
season: unique=2, avg_len=6.00

Target column
class_label_encoded

Input categorical columns
['wind_dir', 'season']

Final columns after one-hot encoding

In [25]:
import numpy as np
import pandas as pd

train_df = pd.read_csv("metadata_split/train_processed_data.csv")
val_df   = pd.read_csv("metadata_split/val_processed_data.csv")
test_df  = pd.read_csv("metadata_split/test_processed_data.csv")

# identify numeric columns
numeric_cols = train_df.select_dtypes(include=[np.number]).columns.tolist()

# fill numeric NaNs using TRAIN medians
train_medians = train_df[numeric_cols].median()

train_df[numeric_cols] = train_df[numeric_cols].fillna(train_medians)
val_df[numeric_cols]   = val_df[numeric_cols].fillna(train_medians)
test_df[numeric_cols]  = test_df[numeric_cols].fillna(train_medians)

print("train total nan:", train_df.isna().sum().sum())
print("val total nan:", val_df.isna().sum().sum())
print("test total nan:", test_df.isna().sum().sum())

# # save cleaned versions
# train_df.to_csv("metadata_split/train_process_clean.csv", index=False)
# val_df.to_csv("metadata_split/val_process_clean.csv", index=False)
# test_df.to_csv("metadata_split/test_process_clean.csv", index=False)

# print("Saved cleaned CSVs.")

train total nan: 0
val total nan: 0
test total nan: 0

In [29]:
train_df.head()

,year,img_f397,img_f492,img_f339,img_f392,img_f142,img_f311,img_f743,img_f888,img_f1947,...,img_f59,img_f679,img_f1419,class_label_encoded,wind_dir_---,wind_dir_N,wind_dir_NNE,wind_dir_SSW,season_Spring,season_Winter
0,2011,0.594061,1.504402,0.000000,0.0,1.114413,0.000005,0.0,0.0,0.849036,...,0.128094,0.000000,0.000000,0,False,False,True,False,False,True
1,2011,0.276269,1.085566,0.000000,0.0,0.868110,0.031464,0.0,0.0,0.138654,...,0.132429,0.077721,0.000000,0,False,False,True,False,False,True
2,2011,1.149455,0.518478,0.000000,0.0,6.389708,0.396701,0.0,0.0,0.007070,...,0.087417,0.023505,0.013536,0,False,False,True,False,False,True
3,2011,0.495224,0.209895,0.046165,0.0,3.614911,0.155939,0.0,0.0,0.112406,...,0.000000,0.087811,0.000000,0,False,False,True,False,False,True
4,2011,0.400659,0.206734,0.021028,0.0,4.472982,0.530318,0.0,0.0,0.133996,...,0.019594,0.002594,0.036342,0,False,False,True,False,False,True

In [30]:
val_df.head()

,year,img_f397,img_f492,img_f339,img_f392,img_f142,img_f311,img_f743,img_f888,img_f1947,...,img_f59,img_f679,img_f1419,class_label_encoded,wind_dir_---,wind_dir_N,wind_dir_NNE,wind_dir_SSW,season_Spring,season_Winter
0,2011,0.239870,0.235464,0.000000,0.0,0.285234,0.120568,0.0,0.000000,0.599407,...,0.088168,0.000000,0.0,0,False,False,True,False,False,True
1,2011,0.267841,0.073997,0.025231,0.0,0.261868,0.041774,0.0,0.000000,0.411599,...,0.327065,0.050561,0.0,0,False,False,True,False,False,True
2,2011,0.491070,0.266679,0.000000,0.0,1.883064,0.121044,0.0,0.000000,0.572409,...,0.207531,0.000000,0.0,0,False,False,True,False,False,True
3,2011,1.087132,0.745814,0.000000,0.0,0.727413,0.183669,0.0,0.030307,0.476472,...,0.121708,0.000000,0.0,0,False,False,True,False,False,True
4,2011,0.288732,0.000142,0.000000,0.0,0.542921,0.039009,0.0,0.000000,0.001757,...,0.000000,0.000000,0.0,0,False,False,True,False,False,True

In [31]:
test_df.head()

,year,img_f397,img_f492,img_f339,img_f392,img_f142,img_f311,img_f743,img_f888,img_f1947,...,img_f59,img_f679,img_f1419,class_label_encoded,wind_dir_---,wind_dir_N,wind_dir_NNE,wind_dir_SSW,season_Spring,season_Winter
0,2012,0.969437,1.980332,0.003121,0.383500,0.348109,0.124442,0.000000,0.008419,0.111737,...,0.592261,0.015116,0.000000,0,False,False,True,False,False,True
1,2012,0.493326,0.379300,0.000000,0.077665,0.141502,0.026641,0.000000,0.000000,0.013809,...,0.787830,0.071438,0.000000,0,False,False,True,False,False,True
2,2012,0.386471,0.466571,0.000000,0.013693,0.910888,0.411789,0.026101,0.023986,0.388476,...,0.906912,0.093578,0.059056,0,False,False,True,False,False,True
3,2012,0.422241,0.104161,0.000000,0.000000,0.865137,0.000000,0.000000,0.000000,0.008571,...,0.567307,0.000000,0.000000,0,False,False,True,False,False,True
4,2012,1.104393,2.181820,0.000000,0.425594,0.559976,0.084818,0.000000,0.085991,0.020233,...,1.692416,0.062241,0.000000,0,False,False,True,False,False,True